using System;
using System.ComponentModel;

namespace SkinCare.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblDonHangChiTiet' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IDonHangChiTiet 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblDonHangChiTiet"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// MaDonHang : 
		/// </summary>
		System.Int32?  MaDonHang  { get; set; }
		
		/// <summary>
		/// MaSanPham : 
		/// </summary>
		System.Int32?  MaSanPham  { get; set; }
		
		/// <summary>
		/// DonGia : 
		/// </summary>
		System.Decimal?  DonGia  { get; set; }
		
		/// <summary>
		/// SoLuong : 
		/// </summary>
		System.Int32?  SoLuong  { get; set; }
		
		/// <summary>
		/// ThanhTien : 
		/// </summary>
		System.Decimal?  ThanhTien  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


