using System;
using System.ComponentModel;

namespace SkinCare.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblKhachHang' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IKhachHang 
	{
		/// <summary>			
		/// MaKhachHang : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblKhachHang"</remarks>
		System.Int32 MaKhachHang { get; set; }
				
		
		
		/// <summary>
		/// TenKhachHang : 
		/// </summary>
		System.String  TenKhachHang  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// SoDienThoai : 
		/// </summary>
		System.String  SoDienThoai  { get; set; }
		
		/// <summary>
		/// DiaChi : 
		/// </summary>
		System.String  DiaChi  { get; set; }
		
		/// <summary>
		/// GioiTinh : 
		/// </summary>
		System.String  GioiTinh  { get; set; }
		
		/// <summary>
		/// LuuY : 
		/// </summary>
		System.String  Luuy  { get; set; }
		
		/// <summary>
		/// ImageLink : 
		/// </summary>
		System.String  ImageLink  { get; set; }
		
		/// <summary>
		/// Ngaysinh : 
		/// </summary>
		System.DateTime?  Ngaysinh  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


