using System;
using System.ComponentModel;

namespace SkinCare.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblKhoHangSanPham' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IKhoHangSanPham 
	{
		/// <summary>			
		/// MaSanPham : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblKhoHangSanPham"</remarks>
		System.Int32 MaSanPham { get; set; }
				
		
		
		/// <summary>
		/// TenSanPham : 
		/// </summary>
		System.String  TenSanPham  { get; set; }
		
		/// <summary>
		/// GiaTien : 
		/// </summary>
		System.Decimal?  GiaTien  { get; set; }
		
		/// <summary>
		/// SoLuongNhapVao : 
		/// </summary>
		System.Int32?  SoLuongNhapVao  { get; set; }
		
		/// <summary>
		/// SoLuongBanRa : 
		/// </summary>
		System.Int32?  SoLuongBanRa  { get; set; }
		
		/// <summary>
		/// SoLuongTonKho : 
		/// </summary>
		System.Int32?  SoLuongTonKho  { get; set; }
		
		/// <summary>
		/// NgayNhapHang : 
		/// </summary>
		System.DateTime?  NgayNhapHang  { get; set; }
		
		/// <summary>
		/// GhiChu : 
		/// </summary>
		System.String  GhiChu  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


