using System;
using System.ComponentModel;

namespace SkinCare.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblKhuyenMai' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IKhuyenMai 
	{
		/// <summary>			
		/// MaKhuyenMai : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblKhuyenMai"</remarks>
		System.Int32 MaKhuyenMai { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalMaKhuyenMai { get; set; }
			
		
		
		/// <summary>
		/// MaLoaiKhuyenMai : 
		/// </summary>
		System.Int32  MaLoaiKhuyenMai  { get; set; }
		
		/// <summary>
		/// TenKhuyenMai : 
		/// </summary>
		System.String  TenKhuyenMai  { get; set; }
		
		/// <summary>
		/// GiaGiam : 
		/// </summary>
		System.Decimal?  GiaGiam  { get; set; }
		
		/// <summary>
		/// NgayTaoKhuyenMai : 
		/// </summary>
		System.DateTime?  NgayTaoKhuyenMai  { get; set; }
		
		/// <summary>
		/// NgayBatDauKhuyenMai : 
		/// </summary>
		System.DateTime?  NgayBatDauKhuyenMai  { get; set; }
		
		/// <summary>
		/// NgayKetThucKhuyenMai : 
		/// </summary>
		System.DateTime?  NgayKetThucKhuyenMai  { get; set; }
		
		/// <summary>
		/// Active : 
		/// </summary>
		System.Boolean?  Active  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


