using System;
using System.ComponentModel;

namespace SkinCare.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblTrangThaiDonHang' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ITrangThaiDonHang 
	{
		/// <summary>			
		/// MaTrangThaiDonHang : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblTrangThaiDonHang"</remarks>
		System.Int32 MaTrangThaiDonHang { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalMaTrangThaiDonHang { get; set; }
			
		
		
		/// <summary>
		/// MaLoaiTrangThaiDonHang : 
		/// </summary>
		System.Int32  MaLoaiTrangThaiDonHang  { get; set; }
		
		/// <summary>
		/// TenLoaiTrangThaiDonHang : Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room
		/// </summary>
		System.String  TenLoaiTrangThaiDonHang  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


