using System;
using System.ComponentModel;

namespace SkinCare.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblUser' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IUser 
	{
		/// <summary>			
		/// UserId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblUser"</remarks>
		System.Int32 UserId { get; set; }
				
		
		
		/// <summary>
		/// UserName : 
		/// </summary>
		System.String  UserName  { get; set; }
		
		/// <summary>
		/// UserRole : 
		/// </summary>
		System.String  UserRole  { get; set; }
		
		/// <summary>
		/// Pwd : 
		/// </summary>
		System.String  Pwd  { get; set; }
		
		/// <summary>
		/// Salt : 
		/// </summary>
		System.String  Salt  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


