
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file KhoHangSanPham.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using SkinCare.Entities.Validation;
#endregion

namespace SkinCare.Entities
{
	///<summary>
	/// An object representation of the 'tblKhoHangSanPham' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class KhoHangSanPhamBase : EntityBase, IKhoHangSanPham, IEntityId<KhoHangSanPhamKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private KhoHangSanPhamEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private KhoHangSanPhamEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private KhoHangSanPhamEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<KhoHangSanPham> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event KhoHangSanPhamEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event KhoHangSanPhamEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="KhoHangSanPhamBase"/> instance.
		///</summary>
		public KhoHangSanPhamBase()
		{
			this.entityData = new KhoHangSanPhamEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="KhoHangSanPhamBase"/> instance.
		///</summary>
		///<param name="_tenSanPham"></param>
		///<param name="_giaTien"></param>
		///<param name="_soLuongNhapVao"></param>
		///<param name="_soLuongBanRa"></param>
		///<param name="_soLuongTonKho"></param>
		///<param name="_ngayNhapHang"></param>
		///<param name="_ghiChu"></param>
		public KhoHangSanPhamBase(System.String _tenSanPham, System.Decimal? _giaTien, 
			System.Int32? _soLuongNhapVao, System.Int32? _soLuongBanRa, System.Int32? _soLuongTonKho, 
			System.DateTime? _ngayNhapHang, System.String _ghiChu)
		{
			this.entityData = new KhoHangSanPhamEntityData();
			this.backupData = null;

			this.TenSanPham = _tenSanPham;
			this.GiaTien = _giaTien;
			this.SoLuongNhapVao = _soLuongNhapVao;
			this.SoLuongBanRa = _soLuongBanRa;
			this.SoLuongTonKho = _soLuongTonKho;
			this.NgayNhapHang = _ngayNhapHang;
			this.GhiChu = _ghiChu;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="KhoHangSanPham"/> instance.
		///</summary>
		///<param name="_tenSanPham"></param>
		///<param name="_giaTien"></param>
		///<param name="_soLuongNhapVao"></param>
		///<param name="_soLuongBanRa"></param>
		///<param name="_soLuongTonKho"></param>
		///<param name="_ngayNhapHang"></param>
		///<param name="_ghiChu"></param>
		public static KhoHangSanPham CreateKhoHangSanPham(System.String _tenSanPham, System.Decimal? _giaTien, 
			System.Int32? _soLuongNhapVao, System.Int32? _soLuongBanRa, System.Int32? _soLuongTonKho, 
			System.DateTime? _ngayNhapHang, System.String _ghiChu)
		{
			KhoHangSanPham newKhoHangSanPham = new KhoHangSanPham();
			newKhoHangSanPham.TenSanPham = _tenSanPham;
			newKhoHangSanPham.GiaTien = _giaTien;
			newKhoHangSanPham.SoLuongNhapVao = _soLuongNhapVao;
			newKhoHangSanPham.SoLuongBanRa = _soLuongBanRa;
			newKhoHangSanPham.SoLuongTonKho = _soLuongTonKho;
			newKhoHangSanPham.NgayNhapHang = _ngayNhapHang;
			newKhoHangSanPham.GhiChu = _ghiChu;
			return newKhoHangSanPham;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaSanPham property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 MaSanPham
		{
			get
			{
				return this.entityData.MaSanPham; 
			}
			
			set
			{
				if (this.entityData.MaSanPham == value)
					return;
				
                OnPropertyChanging("MaSanPham");                    
				OnColumnChanging(KhoHangSanPhamColumn.MaSanPham, this.entityData.MaSanPham);
				this.entityData.MaSanPham = value;
				this.EntityId.MaSanPham = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.MaSanPham, this.entityData.MaSanPham);
				OnPropertyChanged("MaSanPham");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenSanPham property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String TenSanPham
		{
			get
			{
				return this.entityData.TenSanPham; 
			}
			
			set
			{
				if (this.entityData.TenSanPham == value)
					return;
				
                OnPropertyChanging("TenSanPham");                    
				OnColumnChanging(KhoHangSanPhamColumn.TenSanPham, this.entityData.TenSanPham);
				this.entityData.TenSanPham = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.TenSanPham, this.entityData.TenSanPham);
				OnPropertyChanged("TenSanPham");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the GiaTien property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? GiaTien
		{
			get
			{
				return this.entityData.GiaTien; 
			}
			
			set
			{
				if (this.entityData.GiaTien == value)
					return;
				
                OnPropertyChanging("GiaTien");                    
				OnColumnChanging(KhoHangSanPhamColumn.GiaTien, this.entityData.GiaTien);
				this.entityData.GiaTien = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.GiaTien, this.entityData.GiaTien);
				OnPropertyChanged("GiaTien");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SoLuongNhapVao property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? SoLuongNhapVao
		{
			get
			{
				return this.entityData.SoLuongNhapVao; 
			}
			
			set
			{
				if (this.entityData.SoLuongNhapVao == value)
					return;
				
                OnPropertyChanging("SoLuongNhapVao");                    
				OnColumnChanging(KhoHangSanPhamColumn.SoLuongNhapVao, this.entityData.SoLuongNhapVao);
				this.entityData.SoLuongNhapVao = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.SoLuongNhapVao, this.entityData.SoLuongNhapVao);
				OnPropertyChanged("SoLuongNhapVao");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SoLuongBanRa property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? SoLuongBanRa
		{
			get
			{
				return this.entityData.SoLuongBanRa; 
			}
			
			set
			{
				if (this.entityData.SoLuongBanRa == value)
					return;
				
                OnPropertyChanging("SoLuongBanRa");                    
				OnColumnChanging(KhoHangSanPhamColumn.SoLuongBanRa, this.entityData.SoLuongBanRa);
				this.entityData.SoLuongBanRa = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.SoLuongBanRa, this.entityData.SoLuongBanRa);
				OnPropertyChanged("SoLuongBanRa");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SoLuongTonKho property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? SoLuongTonKho
		{
			get
			{
				return this.entityData.SoLuongTonKho; 
			}
			
			set
			{
				if (this.entityData.SoLuongTonKho == value)
					return;
				
                OnPropertyChanging("SoLuongTonKho");                    
				OnColumnChanging(KhoHangSanPhamColumn.SoLuongTonKho, this.entityData.SoLuongTonKho);
				this.entityData.SoLuongTonKho = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.SoLuongTonKho, this.entityData.SoLuongTonKho);
				OnPropertyChanged("SoLuongTonKho");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NgayNhapHang property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? NgayNhapHang
		{
			get
			{
				return this.entityData.NgayNhapHang; 
			}
			
			set
			{
				if (this.entityData.NgayNhapHang == value)
					return;
				
                OnPropertyChanging("NgayNhapHang");                    
				OnColumnChanging(KhoHangSanPhamColumn.NgayNhapHang, this.entityData.NgayNhapHang);
				this.entityData.NgayNhapHang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.NgayNhapHang, this.entityData.NgayNhapHang);
				OnPropertyChanged("NgayNhapHang");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the GhiChu property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String GhiChu
		{
			get
			{
				return this.entityData.GhiChu; 
			}
			
			set
			{
				if (this.entityData.GhiChu == value)
					return;
				
                OnPropertyChanging("GhiChu");                    
				OnColumnChanging(KhoHangSanPhamColumn.GhiChu, this.entityData.GhiChu);
				this.entityData.GhiChu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhoHangSanPhamColumn.GhiChu, this.entityData.GhiChu);
				OnPropertyChanged("GhiChu");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TenSanPham", "Ten San Pham", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblKhoHangSanPham"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaSanPham", "TenSanPham", "GiaTien", "SoLuongNhapVao", "SoLuongBanRa", "SoLuongTonKho", "NgayNhapHang", "GhiChu"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as KhoHangSanPhamEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (KhoHangSanPham) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<KhoHangSanPham>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as KhoHangSanPham);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed KhoHangSanPham Entity 
		///</summary>
		protected virtual KhoHangSanPham Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			KhoHangSanPham copy = new KhoHangSanPham();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MaSanPham = this.MaSanPham;
				copy.TenSanPham = this.TenSanPham;
				copy.GiaTien = this.GiaTien;
				copy.SoLuongNhapVao = this.SoLuongNhapVao;
				copy.SoLuongBanRa = this.SoLuongBanRa;
				copy.SoLuongTonKho = this.SoLuongTonKho;
				copy.NgayNhapHang = this.NgayNhapHang;
				copy.GhiChu = this.GhiChu;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed KhoHangSanPham Entity 
		///</summary>
		public virtual KhoHangSanPham Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed KhoHangSanPham Entity which is a deep copy of the current entity.
		///</summary>
		public virtual KhoHangSanPham DeepCopy()
		{
			return EntityHelper.Clone<KhoHangSanPham>(this as KhoHangSanPham);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as KhoHangSanPhamEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new KhoHangSanPhamEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as KhoHangSanPhamEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(KhoHangSanPhamColumn column)
		{
			switch(column)
			{
					case KhoHangSanPhamColumn.MaSanPham:
					return entityData.MaSanPham != _originalData.MaSanPham;
					case KhoHangSanPhamColumn.TenSanPham:
					return entityData.TenSanPham != _originalData.TenSanPham;
					case KhoHangSanPhamColumn.GiaTien:
					return entityData.GiaTien != _originalData.GiaTien;
					case KhoHangSanPhamColumn.SoLuongNhapVao:
					return entityData.SoLuongNhapVao != _originalData.SoLuongNhapVao;
					case KhoHangSanPhamColumn.SoLuongBanRa:
					return entityData.SoLuongBanRa != _originalData.SoLuongBanRa;
					case KhoHangSanPhamColumn.SoLuongTonKho:
					return entityData.SoLuongTonKho != _originalData.SoLuongTonKho;
					case KhoHangSanPhamColumn.NgayNhapHang:
					return entityData.NgayNhapHang != _originalData.NgayNhapHang;
					case KhoHangSanPhamColumn.GhiChu:
					return entityData.GhiChu != _originalData.GhiChu;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< KhoHangSanPhamColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaSanPham != _originalData.MaSanPham;
			result = result || entityData.TenSanPham != _originalData.TenSanPham;
			result = result || entityData.GiaTien != _originalData.GiaTien;
			result = result || entityData.SoLuongNhapVao != _originalData.SoLuongNhapVao;
			result = result || entityData.SoLuongBanRa != _originalData.SoLuongBanRa;
			result = result || entityData.SoLuongTonKho != _originalData.SoLuongTonKho;
			result = result || entityData.NgayNhapHang != _originalData.NgayNhapHang;
			result = result || entityData.GhiChu != _originalData.GhiChu;
			return result;
		}	
		
		///<summary>
		///  Returns a KhoHangSanPham Entity with the original data.
		///</summary>
		public KhoHangSanPham GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateKhoHangSanPham(
				_originalData.TenSanPham,
				_originalData.GiaTien,
				_originalData.SoLuongNhapVao,
				_originalData.SoLuongBanRa,
				_originalData.SoLuongTonKho,
				_originalData.NgayNhapHang,
				_originalData.GhiChu
				);
				
			return (KhoHangSanPham)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="KhoHangSanPhamBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is KhoHangSanPhamBase)
				return ValueEquals(this, (KhoHangSanPhamBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="KhoHangSanPhamBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaSanPham.GetHashCode() ^ 
					((this.TenSanPham == null) ? string.Empty : this.TenSanPham.ToString()).GetHashCode() ^ 
					((this.GiaTien == null) ? string.Empty : this.GiaTien.ToString()).GetHashCode() ^ 
					((this.SoLuongNhapVao == null) ? string.Empty : this.SoLuongNhapVao.ToString()).GetHashCode() ^ 
					((this.SoLuongBanRa == null) ? string.Empty : this.SoLuongBanRa.ToString()).GetHashCode() ^ 
					((this.SoLuongTonKho == null) ? string.Empty : this.SoLuongTonKho.ToString()).GetHashCode() ^ 
					((this.NgayNhapHang == null) ? string.Empty : this.NgayNhapHang.ToString()).GetHashCode() ^ 
					((this.GhiChu == null) ? string.Empty : this.GhiChu.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="KhoHangSanPhamBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(KhoHangSanPhamBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="KhoHangSanPhamBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="KhoHangSanPhamBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="KhoHangSanPhamBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(KhoHangSanPhamBase Object1, KhoHangSanPhamBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaSanPham != Object2.MaSanPham)
				equal = false;
			if ( Object1.TenSanPham != null && Object2.TenSanPham != null )
			{
				if (Object1.TenSanPham != Object2.TenSanPham)
					equal = false;
			}
			else if (Object1.TenSanPham == null ^ Object2.TenSanPham == null )
			{
				equal = false;
			}
			if ( Object1.GiaTien != null && Object2.GiaTien != null )
			{
				if (Object1.GiaTien != Object2.GiaTien)
					equal = false;
			}
			else if (Object1.GiaTien == null ^ Object2.GiaTien == null )
			{
				equal = false;
			}
			if ( Object1.SoLuongNhapVao != null && Object2.SoLuongNhapVao != null )
			{
				if (Object1.SoLuongNhapVao != Object2.SoLuongNhapVao)
					equal = false;
			}
			else if (Object1.SoLuongNhapVao == null ^ Object2.SoLuongNhapVao == null )
			{
				equal = false;
			}
			if ( Object1.SoLuongBanRa != null && Object2.SoLuongBanRa != null )
			{
				if (Object1.SoLuongBanRa != Object2.SoLuongBanRa)
					equal = false;
			}
			else if (Object1.SoLuongBanRa == null ^ Object2.SoLuongBanRa == null )
			{
				equal = false;
			}
			if ( Object1.SoLuongTonKho != null && Object2.SoLuongTonKho != null )
			{
				if (Object1.SoLuongTonKho != Object2.SoLuongTonKho)
					equal = false;
			}
			else if (Object1.SoLuongTonKho == null ^ Object2.SoLuongTonKho == null )
			{
				equal = false;
			}
			if ( Object1.NgayNhapHang != null && Object2.NgayNhapHang != null )
			{
				if (Object1.NgayNhapHang != Object2.NgayNhapHang)
					equal = false;
			}
			else if (Object1.NgayNhapHang == null ^ Object2.NgayNhapHang == null )
			{
				equal = false;
			}
			if ( Object1.GhiChu != null && Object2.GhiChu != null )
			{
				if (Object1.GhiChu != Object2.GhiChu)
					equal = false;
			}
			else if (Object1.GhiChu == null ^ Object2.GhiChu == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((KhoHangSanPhamBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static KhoHangSanPhamComparer GetComparer()
        {
            return new KhoHangSanPhamComparer();
        }
        */

        // Comparer delegates back to KhoHangSanPham
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(KhoHangSanPham rhs, KhoHangSanPhamColumn which)
        {
            switch (which)
            {
            	
            	
            	case KhoHangSanPhamColumn.MaSanPham:
            		return this.MaSanPham.CompareTo(rhs.MaSanPham);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.TenSanPham:
            		return this.TenSanPham.CompareTo(rhs.TenSanPham);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.GiaTien:
            		return this.GiaTien.Value.CompareTo(rhs.GiaTien.Value);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.SoLuongNhapVao:
            		return this.SoLuongNhapVao.Value.CompareTo(rhs.SoLuongNhapVao.Value);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.SoLuongBanRa:
            		return this.SoLuongBanRa.Value.CompareTo(rhs.SoLuongBanRa.Value);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.SoLuongTonKho:
            		return this.SoLuongTonKho.Value.CompareTo(rhs.SoLuongTonKho.Value);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.NgayNhapHang:
            		return this.NgayNhapHang.Value.CompareTo(rhs.NgayNhapHang.Value);
            		
            		                 
            	
            	
            	case KhoHangSanPhamColumn.GhiChu:
            		return this.GhiChu.CompareTo(rhs.GhiChu);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<KhoHangSanPhamKey> Members
		
		// member variable for the EntityId property
		private KhoHangSanPhamKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual KhoHangSanPhamKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new KhoHangSanPhamKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("KhoHangSanPham")
					.Append("|").Append( this.MaSanPham.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- MaSanPham: {0}{8}- TenSanPham: {1}{8}- GiaTien: {2}{8}- SoLuongNhapVao: {3}{8}- SoLuongBanRa: {4}{8}- SoLuongTonKho: {5}{8}- NgayNhapHang: {6}{8}- GhiChu: {7}{8}{10}", 
				this.MaSanPham,
				(this.TenSanPham == null) ? string.Empty : this.TenSanPham.ToString(),
				(this.GiaTien == null) ? string.Empty : this.GiaTien.ToString(),
				(this.SoLuongNhapVao == null) ? string.Empty : this.SoLuongNhapVao.ToString(),
				(this.SoLuongBanRa == null) ? string.Empty : this.SoLuongBanRa.ToString(),
				(this.SoLuongTonKho == null) ? string.Empty : this.SoLuongTonKho.ToString(),
				(this.NgayNhapHang == null) ? string.Empty : this.NgayNhapHang.ToString(),
				(this.GhiChu == null) ? string.Empty : this.GhiChu.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblKhoHangSanPham' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class KhoHangSanPhamEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MaSanPham : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblKhoHangSanPham"</remarks>
		public System.Int32 MaSanPham;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// TenSanPham : 
		/// </summary>
		public System.String TenSanPham = null;
		
		/// <summary>
		/// GiaTien : 
		/// </summary>
		public System.Decimal? GiaTien = null;
		
		/// <summary>
		/// SoLuongNhapVao : 
		/// </summary>
		public System.Int32? SoLuongNhapVao = null;
		
		/// <summary>
		/// SoLuongBanRa : 
		/// </summary>
		public System.Int32? SoLuongBanRa = null;
		
		/// <summary>
		/// SoLuongTonKho : 
		/// </summary>
		public System.Int32? SoLuongTonKho = null;
		
		/// <summary>
		/// NgayNhapHang : 
		/// </summary>
		public System.DateTime? NgayNhapHang = null;
		
		/// <summary>
		/// GhiChu : 
		/// </summary>
		public System.String GhiChu = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			KhoHangSanPhamEntityData _tmp = new KhoHangSanPhamEntityData();
						
			_tmp.MaSanPham = this.MaSanPham;
			
			_tmp.TenSanPham = this.TenSanPham;
			_tmp.GiaTien = this.GiaTien;
			_tmp.SoLuongNhapVao = this.SoLuongNhapVao;
			_tmp.SoLuongBanRa = this.SoLuongBanRa;
			_tmp.SoLuongTonKho = this.SoLuongTonKho;
			_tmp.NgayNhapHang = this.NgayNhapHang;
			_tmp.GhiChu = this.GhiChu;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			KhoHangSanPhamEntityData _tmp = new KhoHangSanPhamEntityData();
						
			_tmp.MaSanPham = this.MaSanPham;
			
			_tmp.TenSanPham = this.TenSanPham;
			_tmp.GiaTien = this.GiaTien;
			_tmp.SoLuongNhapVao = this.SoLuongNhapVao;
			_tmp.SoLuongBanRa = this.SoLuongBanRa;
			_tmp.SoLuongTonKho = this.SoLuongTonKho;
			_tmp.NgayNhapHang = this.NgayNhapHang;
			_tmp.GhiChu = this.GhiChu;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhoHangSanPhamColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(KhoHangSanPhamColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhoHangSanPhamColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(KhoHangSanPhamColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhoHangSanPhamColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(KhoHangSanPhamColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				KhoHangSanPhamEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new KhoHangSanPhamEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhoHangSanPhamColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(KhoHangSanPhamColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				KhoHangSanPhamEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new KhoHangSanPhamEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region KhoHangSanPhamEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="KhoHangSanPham"/> object.
	/// </remarks>
	public class KhoHangSanPhamEventArgs : System.EventArgs
	{
		private KhoHangSanPhamColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the KhoHangSanPhamEventArgs class.
		///</summary>
		public KhoHangSanPhamEventArgs(KhoHangSanPhamColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the KhoHangSanPhamEventArgs class.
		///</summary>
		public KhoHangSanPhamEventArgs(KhoHangSanPhamColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The KhoHangSanPhamColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="KhoHangSanPhamColumn" />
		public KhoHangSanPhamColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all KhoHangSanPham related events.
	///</summary>
	public delegate void KhoHangSanPhamEventHandler(object sender, KhoHangSanPhamEventArgs e);
	
	#region KhoHangSanPhamComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class KhoHangSanPhamComparer : System.Collections.Generic.IComparer<KhoHangSanPham>
	{
		KhoHangSanPhamColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:KhoHangSanPhamComparer"/> class.
        /// </summary>
		public KhoHangSanPhamComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:KhoHangSanPhamComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public KhoHangSanPhamComparer(KhoHangSanPhamColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="KhoHangSanPham"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="KhoHangSanPham"/> to compare.</param>
        /// <param name="b">The second <c>KhoHangSanPham</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(KhoHangSanPham a, KhoHangSanPham b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(KhoHangSanPham entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(KhoHangSanPham a, KhoHangSanPham b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public KhoHangSanPhamColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region KhoHangSanPhamKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="KhoHangSanPham"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class KhoHangSanPhamKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the KhoHangSanPhamKey class.
		/// </summary>
		public KhoHangSanPhamKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the KhoHangSanPhamKey class.
		/// </summary>
		public KhoHangSanPhamKey(KhoHangSanPhamBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaSanPham = entity.MaSanPham;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the KhoHangSanPhamKey class.
		/// </summary>
		public KhoHangSanPhamKey(System.Int32 _maSanPham)
		{
			#region Init Properties

			this.MaSanPham = _maSanPham;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private KhoHangSanPhamBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public KhoHangSanPhamBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaSanPham property
		private System.Int32 _maSanPham;
		
		/// <summary>
		/// Gets or sets the MaSanPham property.
		/// </summary>
		public System.Int32 MaSanPham
		{
			get { return _maSanPham; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaSanPham = value;
				
				_maSanPham = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaSanPham = ( values["MaSanPham"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MaSanPham"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaSanPham", MaSanPham);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaSanPham: {0}{1}",
								MaSanPham,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region KhoHangSanPhamColumn Enum
	
	/// <summary>
	/// Enumerate the KhoHangSanPham columns.
	/// </summary>
	[Serializable]
	public enum KhoHangSanPhamColumn : int
	{
		/// <summary>
		/// MaSanPham : 
		/// </summary>
		[EnumTextValue("Ma San Pham")]
		[ColumnEnum("MaSanPham", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		MaSanPham = 1,
		/// <summary>
		/// TenSanPham : 
		/// </summary>
		[EnumTextValue("Ten San Pham")]
		[ColumnEnum("TenSanPham", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		TenSanPham = 2,
		/// <summary>
		/// GiaTien : 
		/// </summary>
		[EnumTextValue("Gia Tien")]
		[ColumnEnum("GiaTien", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		GiaTien = 3,
		/// <summary>
		/// SoLuongNhapVao : 
		/// </summary>
		[EnumTextValue("So Luong Nhap Vao")]
		[ColumnEnum("SoLuongNhapVao", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		SoLuongNhapVao = 4,
		/// <summary>
		/// SoLuongBanRa : 
		/// </summary>
		[EnumTextValue("So Luong Ban Ra")]
		[ColumnEnum("SoLuongBanRa", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		SoLuongBanRa = 5,
		/// <summary>
		/// SoLuongTonKho : 
		/// </summary>
		[EnumTextValue("So Luong Ton Kho")]
		[ColumnEnum("SoLuongTonKho", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		SoLuongTonKho = 6,
		/// <summary>
		/// NgayNhapHang : 
		/// </summary>
		[EnumTextValue("Ngay Nhap Hang")]
		[ColumnEnum("NgayNhapHang", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		NgayNhapHang = 7,
		/// <summary>
		/// GhiChu : 
		/// </summary>
		[EnumTextValue("Ghi Chu")]
		[ColumnEnum("GhiChu", typeof(System.String), System.Data.DbType.String, false, false, true)]
		GhiChu = 8
	}//End enum

	#endregion KhoHangSanPhamColumn Enum

} // end namespace
