
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file KhuyenMai.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using SkinCare.Entities.Validation;
#endregion

namespace SkinCare.Entities
{
	///<summary>
	/// An object representation of the 'tblKhuyenMai' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class KhuyenMaiBase : EntityBase, IKhuyenMai, IEntityId<KhuyenMaiKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private KhuyenMaiEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private KhuyenMaiEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private KhuyenMaiEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<KhuyenMai> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event KhuyenMaiEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event KhuyenMaiEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="KhuyenMaiBase"/> instance.
		///</summary>
		public KhuyenMaiBase()
		{
			this.entityData = new KhuyenMaiEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="KhuyenMaiBase"/> instance.
		///</summary>
		///<param name="_maKhuyenMai"></param>
		///<param name="_maLoaiKhuyenMai"></param>
		///<param name="_tenKhuyenMai"></param>
		///<param name="_giaGiam"></param>
		///<param name="_ngayTaoKhuyenMai"></param>
		///<param name="_ngayBatDauKhuyenMai"></param>
		///<param name="_ngayKetThucKhuyenMai"></param>
		///<param name="_active"></param>
		public KhuyenMaiBase(System.Int32 _maKhuyenMai, System.Int32 _maLoaiKhuyenMai, 
			System.String _tenKhuyenMai, System.Decimal? _giaGiam, System.DateTime? _ngayTaoKhuyenMai, 
			System.DateTime? _ngayBatDauKhuyenMai, System.DateTime? _ngayKetThucKhuyenMai, System.Boolean? _active)
		{
			this.entityData = new KhuyenMaiEntityData();
			this.backupData = null;

			this.MaKhuyenMai = _maKhuyenMai;
			this.MaLoaiKhuyenMai = _maLoaiKhuyenMai;
			this.TenKhuyenMai = _tenKhuyenMai;
			this.GiaGiam = _giaGiam;
			this.NgayTaoKhuyenMai = _ngayTaoKhuyenMai;
			this.NgayBatDauKhuyenMai = _ngayBatDauKhuyenMai;
			this.NgayKetThucKhuyenMai = _ngayKetThucKhuyenMai;
			this.Active = _active;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="KhuyenMai"/> instance.
		///</summary>
		///<param name="_maKhuyenMai"></param>
		///<param name="_maLoaiKhuyenMai"></param>
		///<param name="_tenKhuyenMai"></param>
		///<param name="_giaGiam"></param>
		///<param name="_ngayTaoKhuyenMai"></param>
		///<param name="_ngayBatDauKhuyenMai"></param>
		///<param name="_ngayKetThucKhuyenMai"></param>
		///<param name="_active"></param>
		public static KhuyenMai CreateKhuyenMai(System.Int32 _maKhuyenMai, System.Int32 _maLoaiKhuyenMai, 
			System.String _tenKhuyenMai, System.Decimal? _giaGiam, System.DateTime? _ngayTaoKhuyenMai, 
			System.DateTime? _ngayBatDauKhuyenMai, System.DateTime? _ngayKetThucKhuyenMai, System.Boolean? _active)
		{
			KhuyenMai newKhuyenMai = new KhuyenMai();
			newKhuyenMai.MaKhuyenMai = _maKhuyenMai;
			newKhuyenMai.MaLoaiKhuyenMai = _maLoaiKhuyenMai;
			newKhuyenMai.TenKhuyenMai = _tenKhuyenMai;
			newKhuyenMai.GiaGiam = _giaGiam;
			newKhuyenMai.NgayTaoKhuyenMai = _ngayTaoKhuyenMai;
			newKhuyenMai.NgayBatDauKhuyenMai = _ngayBatDauKhuyenMai;
			newKhuyenMai.NgayKetThucKhuyenMai = _ngayKetThucKhuyenMai;
			newKhuyenMai.Active = _active;
			return newKhuyenMai;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaKhuyenMai property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 MaKhuyenMai
		{
			get
			{
				return this.entityData.MaKhuyenMai; 
			}
			
			set
			{
				if (this.entityData.MaKhuyenMai == value)
					return;
				
                OnPropertyChanging("MaKhuyenMai");                    
				OnColumnChanging(KhuyenMaiColumn.MaKhuyenMai, this.entityData.MaKhuyenMai);
				this.entityData.MaKhuyenMai = value;
				this.EntityId.MaKhuyenMai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.MaKhuyenMai, this.entityData.MaKhuyenMai);
				OnPropertyChanged("MaKhuyenMai");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MaKhuyenMai property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MaKhuyenMai property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalMaKhuyenMai
		{
			get { return this.entityData.OriginalMaKhuyenMai; }
			set { this.entityData.OriginalMaKhuyenMai = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the MaLoaiKhuyenMai property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 MaLoaiKhuyenMai
		{
			get
			{
				return this.entityData.MaLoaiKhuyenMai; 
			}
			
			set
			{
				if (this.entityData.MaLoaiKhuyenMai == value)
					return;
				
                OnPropertyChanging("MaLoaiKhuyenMai");                    
				OnColumnChanging(KhuyenMaiColumn.MaLoaiKhuyenMai, this.entityData.MaLoaiKhuyenMai);
				this.entityData.MaLoaiKhuyenMai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.MaLoaiKhuyenMai, this.entityData.MaLoaiKhuyenMai);
				OnPropertyChanged("MaLoaiKhuyenMai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenKhuyenMai property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String TenKhuyenMai
		{
			get
			{
				return this.entityData.TenKhuyenMai; 
			}
			
			set
			{
				if (this.entityData.TenKhuyenMai == value)
					return;
				
                OnPropertyChanging("TenKhuyenMai");                    
				OnColumnChanging(KhuyenMaiColumn.TenKhuyenMai, this.entityData.TenKhuyenMai);
				this.entityData.TenKhuyenMai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.TenKhuyenMai, this.entityData.TenKhuyenMai);
				OnPropertyChanged("TenKhuyenMai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the GiaGiam property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? GiaGiam
		{
			get
			{
				return this.entityData.GiaGiam; 
			}
			
			set
			{
				if (this.entityData.GiaGiam == value)
					return;
				
                OnPropertyChanging("GiaGiam");                    
				OnColumnChanging(KhuyenMaiColumn.GiaGiam, this.entityData.GiaGiam);
				this.entityData.GiaGiam = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.GiaGiam, this.entityData.GiaGiam);
				OnPropertyChanged("GiaGiam");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NgayTaoKhuyenMai property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? NgayTaoKhuyenMai
		{
			get
			{
				return this.entityData.NgayTaoKhuyenMai; 
			}
			
			set
			{
				if (this.entityData.NgayTaoKhuyenMai == value)
					return;
				
                OnPropertyChanging("NgayTaoKhuyenMai");                    
				OnColumnChanging(KhuyenMaiColumn.NgayTaoKhuyenMai, this.entityData.NgayTaoKhuyenMai);
				this.entityData.NgayTaoKhuyenMai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.NgayTaoKhuyenMai, this.entityData.NgayTaoKhuyenMai);
				OnPropertyChanged("NgayTaoKhuyenMai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NgayBatDauKhuyenMai property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? NgayBatDauKhuyenMai
		{
			get
			{
				return this.entityData.NgayBatDauKhuyenMai; 
			}
			
			set
			{
				if (this.entityData.NgayBatDauKhuyenMai == value)
					return;
				
                OnPropertyChanging("NgayBatDauKhuyenMai");                    
				OnColumnChanging(KhuyenMaiColumn.NgayBatDauKhuyenMai, this.entityData.NgayBatDauKhuyenMai);
				this.entityData.NgayBatDauKhuyenMai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.NgayBatDauKhuyenMai, this.entityData.NgayBatDauKhuyenMai);
				OnPropertyChanged("NgayBatDauKhuyenMai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NgayKetThucKhuyenMai property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? NgayKetThucKhuyenMai
		{
			get
			{
				return this.entityData.NgayKetThucKhuyenMai; 
			}
			
			set
			{
				if (this.entityData.NgayKetThucKhuyenMai == value)
					return;
				
                OnPropertyChanging("NgayKetThucKhuyenMai");                    
				OnColumnChanging(KhuyenMaiColumn.NgayKetThucKhuyenMai, this.entityData.NgayKetThucKhuyenMai);
				this.entityData.NgayKetThucKhuyenMai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.NgayKetThucKhuyenMai, this.entityData.NgayKetThucKhuyenMai);
				OnPropertyChanged("NgayKetThucKhuyenMai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Active property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Active
		{
			get
			{
				return this.entityData.Active; 
			}
			
			set
			{
				if (this.entityData.Active == value)
					return;
				
                OnPropertyChanging("Active");                    
				OnColumnChanging(KhuyenMaiColumn.Active, this.entityData.Active);
				this.entityData.Active = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(KhuyenMaiColumn.Active, this.entityData.Active);
				OnPropertyChanged("Active");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TenKhuyenMai", "Ten Khuyen Mai", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblKhuyenMai"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaKhuyenMai", "MaLoaiKhuyenMai", "TenKhuyenMai", "GiaGiam", "NgayTaoKhuyenMai", "NgayBatDauKhuyenMai", "NgayKetThucKhuyenMai", "Active"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as KhuyenMaiEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (KhuyenMai) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<KhuyenMai>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as KhuyenMai);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed KhuyenMai Entity 
		///</summary>
		protected virtual KhuyenMai Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			KhuyenMai copy = new KhuyenMai();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MaKhuyenMai = this.MaKhuyenMai;
					copy.OriginalMaKhuyenMai = this.OriginalMaKhuyenMai;
				copy.MaLoaiKhuyenMai = this.MaLoaiKhuyenMai;
				copy.TenKhuyenMai = this.TenKhuyenMai;
				copy.GiaGiam = this.GiaGiam;
				copy.NgayTaoKhuyenMai = this.NgayTaoKhuyenMai;
				copy.NgayBatDauKhuyenMai = this.NgayBatDauKhuyenMai;
				copy.NgayKetThucKhuyenMai = this.NgayKetThucKhuyenMai;
				copy.Active = this.Active;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed KhuyenMai Entity 
		///</summary>
		public virtual KhuyenMai Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed KhuyenMai Entity which is a deep copy of the current entity.
		///</summary>
		public virtual KhuyenMai DeepCopy()
		{
			return EntityHelper.Clone<KhuyenMai>(this as KhuyenMai);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as KhuyenMaiEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new KhuyenMaiEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as KhuyenMaiEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(KhuyenMaiColumn column)
		{
			switch(column)
			{
					case KhuyenMaiColumn.MaKhuyenMai:
					return entityData.MaKhuyenMai != _originalData.MaKhuyenMai;
					case KhuyenMaiColumn.MaLoaiKhuyenMai:
					return entityData.MaLoaiKhuyenMai != _originalData.MaLoaiKhuyenMai;
					case KhuyenMaiColumn.TenKhuyenMai:
					return entityData.TenKhuyenMai != _originalData.TenKhuyenMai;
					case KhuyenMaiColumn.GiaGiam:
					return entityData.GiaGiam != _originalData.GiaGiam;
					case KhuyenMaiColumn.NgayTaoKhuyenMai:
					return entityData.NgayTaoKhuyenMai != _originalData.NgayTaoKhuyenMai;
					case KhuyenMaiColumn.NgayBatDauKhuyenMai:
					return entityData.NgayBatDauKhuyenMai != _originalData.NgayBatDauKhuyenMai;
					case KhuyenMaiColumn.NgayKetThucKhuyenMai:
					return entityData.NgayKetThucKhuyenMai != _originalData.NgayKetThucKhuyenMai;
					case KhuyenMaiColumn.Active:
					return entityData.Active != _originalData.Active;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< KhuyenMaiColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaKhuyenMai != _originalData.MaKhuyenMai;
			result = result || entityData.MaLoaiKhuyenMai != _originalData.MaLoaiKhuyenMai;
			result = result || entityData.TenKhuyenMai != _originalData.TenKhuyenMai;
			result = result || entityData.GiaGiam != _originalData.GiaGiam;
			result = result || entityData.NgayTaoKhuyenMai != _originalData.NgayTaoKhuyenMai;
			result = result || entityData.NgayBatDauKhuyenMai != _originalData.NgayBatDauKhuyenMai;
			result = result || entityData.NgayKetThucKhuyenMai != _originalData.NgayKetThucKhuyenMai;
			result = result || entityData.Active != _originalData.Active;
			return result;
		}	
		
		///<summary>
		///  Returns a KhuyenMai Entity with the original data.
		///</summary>
		public KhuyenMai GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateKhuyenMai(
				_originalData.MaKhuyenMai,
				_originalData.MaLoaiKhuyenMai,
				_originalData.TenKhuyenMai,
				_originalData.GiaGiam,
				_originalData.NgayTaoKhuyenMai,
				_originalData.NgayBatDauKhuyenMai,
				_originalData.NgayKetThucKhuyenMai,
				_originalData.Active
				);
				
			return (KhuyenMai)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="KhuyenMaiBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is KhuyenMaiBase)
				return ValueEquals(this, (KhuyenMaiBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="KhuyenMaiBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaKhuyenMai.GetHashCode() ^ 
					this.MaLoaiKhuyenMai.GetHashCode() ^ 
					((this.TenKhuyenMai == null) ? string.Empty : this.TenKhuyenMai.ToString()).GetHashCode() ^ 
					((this.GiaGiam == null) ? string.Empty : this.GiaGiam.ToString()).GetHashCode() ^ 
					((this.NgayTaoKhuyenMai == null) ? string.Empty : this.NgayTaoKhuyenMai.ToString()).GetHashCode() ^ 
					((this.NgayBatDauKhuyenMai == null) ? string.Empty : this.NgayBatDauKhuyenMai.ToString()).GetHashCode() ^ 
					((this.NgayKetThucKhuyenMai == null) ? string.Empty : this.NgayKetThucKhuyenMai.ToString()).GetHashCode() ^ 
					((this.Active == null) ? string.Empty : this.Active.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="KhuyenMaiBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(KhuyenMaiBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="KhuyenMaiBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="KhuyenMaiBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="KhuyenMaiBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(KhuyenMaiBase Object1, KhuyenMaiBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaKhuyenMai != Object2.MaKhuyenMai)
				equal = false;
			if (Object1.MaLoaiKhuyenMai != Object2.MaLoaiKhuyenMai)
				equal = false;
			if ( Object1.TenKhuyenMai != null && Object2.TenKhuyenMai != null )
			{
				if (Object1.TenKhuyenMai != Object2.TenKhuyenMai)
					equal = false;
			}
			else if (Object1.TenKhuyenMai == null ^ Object2.TenKhuyenMai == null )
			{
				equal = false;
			}
			if ( Object1.GiaGiam != null && Object2.GiaGiam != null )
			{
				if (Object1.GiaGiam != Object2.GiaGiam)
					equal = false;
			}
			else if (Object1.GiaGiam == null ^ Object2.GiaGiam == null )
			{
				equal = false;
			}
			if ( Object1.NgayTaoKhuyenMai != null && Object2.NgayTaoKhuyenMai != null )
			{
				if (Object1.NgayTaoKhuyenMai != Object2.NgayTaoKhuyenMai)
					equal = false;
			}
			else if (Object1.NgayTaoKhuyenMai == null ^ Object2.NgayTaoKhuyenMai == null )
			{
				equal = false;
			}
			if ( Object1.NgayBatDauKhuyenMai != null && Object2.NgayBatDauKhuyenMai != null )
			{
				if (Object1.NgayBatDauKhuyenMai != Object2.NgayBatDauKhuyenMai)
					equal = false;
			}
			else if (Object1.NgayBatDauKhuyenMai == null ^ Object2.NgayBatDauKhuyenMai == null )
			{
				equal = false;
			}
			if ( Object1.NgayKetThucKhuyenMai != null && Object2.NgayKetThucKhuyenMai != null )
			{
				if (Object1.NgayKetThucKhuyenMai != Object2.NgayKetThucKhuyenMai)
					equal = false;
			}
			else if (Object1.NgayKetThucKhuyenMai == null ^ Object2.NgayKetThucKhuyenMai == null )
			{
				equal = false;
			}
			if ( Object1.Active != null && Object2.Active != null )
			{
				if (Object1.Active != Object2.Active)
					equal = false;
			}
			else if (Object1.Active == null ^ Object2.Active == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((KhuyenMaiBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static KhuyenMaiComparer GetComparer()
        {
            return new KhuyenMaiComparer();
        }
        */

        // Comparer delegates back to KhuyenMai
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(KhuyenMai rhs, KhuyenMaiColumn which)
        {
            switch (which)
            {
            	
            	
            	case KhuyenMaiColumn.MaKhuyenMai:
            		return this.MaKhuyenMai.CompareTo(rhs.MaKhuyenMai);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.MaLoaiKhuyenMai:
            		return this.MaLoaiKhuyenMai.CompareTo(rhs.MaLoaiKhuyenMai);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.TenKhuyenMai:
            		return this.TenKhuyenMai.CompareTo(rhs.TenKhuyenMai);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.GiaGiam:
            		return this.GiaGiam.Value.CompareTo(rhs.GiaGiam.Value);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.NgayTaoKhuyenMai:
            		return this.NgayTaoKhuyenMai.Value.CompareTo(rhs.NgayTaoKhuyenMai.Value);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.NgayBatDauKhuyenMai:
            		return this.NgayBatDauKhuyenMai.Value.CompareTo(rhs.NgayBatDauKhuyenMai.Value);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.NgayKetThucKhuyenMai:
            		return this.NgayKetThucKhuyenMai.Value.CompareTo(rhs.NgayKetThucKhuyenMai.Value);
            		
            		                 
            	
            	
            	case KhuyenMaiColumn.Active:
            		return this.Active.Value.CompareTo(rhs.Active.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<KhuyenMaiKey> Members
		
		// member variable for the EntityId property
		private KhuyenMaiKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual KhuyenMaiKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new KhuyenMaiKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("KhuyenMai")
					.Append("|").Append( this.MaKhuyenMai.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- MaKhuyenMai: {0}{8}- MaLoaiKhuyenMai: {1}{8}- TenKhuyenMai: {2}{8}- GiaGiam: {3}{8}- NgayTaoKhuyenMai: {4}{8}- NgayBatDauKhuyenMai: {5}{8}- NgayKetThucKhuyenMai: {6}{8}- Active: {7}{8}{10}", 
				this.MaKhuyenMai,
				this.MaLoaiKhuyenMai,
				(this.TenKhuyenMai == null) ? string.Empty : this.TenKhuyenMai.ToString(),
				(this.GiaGiam == null) ? string.Empty : this.GiaGiam.ToString(),
				(this.NgayTaoKhuyenMai == null) ? string.Empty : this.NgayTaoKhuyenMai.ToString(),
				(this.NgayBatDauKhuyenMai == null) ? string.Empty : this.NgayBatDauKhuyenMai.ToString(),
				(this.NgayKetThucKhuyenMai == null) ? string.Empty : this.NgayKetThucKhuyenMai.ToString(),
				(this.Active == null) ? string.Empty : this.Active.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblKhuyenMai' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class KhuyenMaiEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MaKhuyenMai : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblKhuyenMai"</remarks>
		public System.Int32 MaKhuyenMai;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalMaKhuyenMai;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaLoaiKhuyenMai : 
		/// </summary>
		public System.Int32 MaLoaiKhuyenMai = (int)0;
		
		/// <summary>
		/// TenKhuyenMai : 
		/// </summary>
		public System.String TenKhuyenMai = null;
		
		/// <summary>
		/// GiaGiam : 
		/// </summary>
		public System.Decimal? GiaGiam = null;
		
		/// <summary>
		/// NgayTaoKhuyenMai : 
		/// </summary>
		public System.DateTime? NgayTaoKhuyenMai = null;
		
		/// <summary>
		/// NgayBatDauKhuyenMai : 
		/// </summary>
		public System.DateTime? NgayBatDauKhuyenMai = null;
		
		/// <summary>
		/// NgayKetThucKhuyenMai : 
		/// </summary>
		public System.DateTime? NgayKetThucKhuyenMai = null;
		
		/// <summary>
		/// Active : 
		/// </summary>
		public System.Boolean? Active = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			KhuyenMaiEntityData _tmp = new KhuyenMaiEntityData();
						
			_tmp.MaKhuyenMai = this.MaKhuyenMai;
			_tmp.OriginalMaKhuyenMai = this.OriginalMaKhuyenMai;
			
			_tmp.MaLoaiKhuyenMai = this.MaLoaiKhuyenMai;
			_tmp.TenKhuyenMai = this.TenKhuyenMai;
			_tmp.GiaGiam = this.GiaGiam;
			_tmp.NgayTaoKhuyenMai = this.NgayTaoKhuyenMai;
			_tmp.NgayBatDauKhuyenMai = this.NgayBatDauKhuyenMai;
			_tmp.NgayKetThucKhuyenMai = this.NgayKetThucKhuyenMai;
			_tmp.Active = this.Active;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			KhuyenMaiEntityData _tmp = new KhuyenMaiEntityData();
						
			_tmp.MaKhuyenMai = this.MaKhuyenMai;
			_tmp.OriginalMaKhuyenMai = this.OriginalMaKhuyenMai;
			
			_tmp.MaLoaiKhuyenMai = this.MaLoaiKhuyenMai;
			_tmp.TenKhuyenMai = this.TenKhuyenMai;
			_tmp.GiaGiam = this.GiaGiam;
			_tmp.NgayTaoKhuyenMai = this.NgayTaoKhuyenMai;
			_tmp.NgayBatDauKhuyenMai = this.NgayBatDauKhuyenMai;
			_tmp.NgayKetThucKhuyenMai = this.NgayKetThucKhuyenMai;
			_tmp.Active = this.Active;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhuyenMaiColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(KhuyenMaiColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhuyenMaiColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(KhuyenMaiColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhuyenMaiColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(KhuyenMaiColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				KhuyenMaiEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new KhuyenMaiEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="KhuyenMaiColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(KhuyenMaiColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				KhuyenMaiEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new KhuyenMaiEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region KhuyenMaiEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="KhuyenMai"/> object.
	/// </remarks>
	public class KhuyenMaiEventArgs : System.EventArgs
	{
		private KhuyenMaiColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the KhuyenMaiEventArgs class.
		///</summary>
		public KhuyenMaiEventArgs(KhuyenMaiColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the KhuyenMaiEventArgs class.
		///</summary>
		public KhuyenMaiEventArgs(KhuyenMaiColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The KhuyenMaiColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="KhuyenMaiColumn" />
		public KhuyenMaiColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all KhuyenMai related events.
	///</summary>
	public delegate void KhuyenMaiEventHandler(object sender, KhuyenMaiEventArgs e);
	
	#region KhuyenMaiComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class KhuyenMaiComparer : System.Collections.Generic.IComparer<KhuyenMai>
	{
		KhuyenMaiColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:KhuyenMaiComparer"/> class.
        /// </summary>
		public KhuyenMaiComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:KhuyenMaiComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public KhuyenMaiComparer(KhuyenMaiColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="KhuyenMai"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="KhuyenMai"/> to compare.</param>
        /// <param name="b">The second <c>KhuyenMai</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(KhuyenMai a, KhuyenMai b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(KhuyenMai entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(KhuyenMai a, KhuyenMai b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public KhuyenMaiColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region KhuyenMaiKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="KhuyenMai"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class KhuyenMaiKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the KhuyenMaiKey class.
		/// </summary>
		public KhuyenMaiKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the KhuyenMaiKey class.
		/// </summary>
		public KhuyenMaiKey(KhuyenMaiBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaKhuyenMai = entity.MaKhuyenMai;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the KhuyenMaiKey class.
		/// </summary>
		public KhuyenMaiKey(System.Int32 _maKhuyenMai)
		{
			#region Init Properties

			this.MaKhuyenMai = _maKhuyenMai;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private KhuyenMaiBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public KhuyenMaiBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaKhuyenMai property
		private System.Int32 _maKhuyenMai;
		
		/// <summary>
		/// Gets or sets the MaKhuyenMai property.
		/// </summary>
		public System.Int32 MaKhuyenMai
		{
			get { return _maKhuyenMai; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaKhuyenMai = value;
				
				_maKhuyenMai = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaKhuyenMai = ( values["MaKhuyenMai"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MaKhuyenMai"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaKhuyenMai", MaKhuyenMai);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaKhuyenMai: {0}{1}",
								MaKhuyenMai,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region KhuyenMaiColumn Enum
	
	/// <summary>
	/// Enumerate the KhuyenMai columns.
	/// </summary>
	[Serializable]
	public enum KhuyenMaiColumn : int
	{
		/// <summary>
		/// MaKhuyenMai : 
		/// </summary>
		[EnumTextValue("Ma Khuyen Mai")]
		[ColumnEnum("MaKhuyenMai", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		MaKhuyenMai = 1,
		/// <summary>
		/// MaLoaiKhuyenMai : 
		/// </summary>
		[EnumTextValue("Ma Loai Khuyen Mai")]
		[ColumnEnum("MaLoaiKhuyenMai", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		MaLoaiKhuyenMai = 2,
		/// <summary>
		/// TenKhuyenMai : 
		/// </summary>
		[EnumTextValue("Ten Khuyen Mai")]
		[ColumnEnum("TenKhuyenMai", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		TenKhuyenMai = 3,
		/// <summary>
		/// GiaGiam : 
		/// </summary>
		[EnumTextValue("Gia Giam")]
		[ColumnEnum("GiaGiam", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		GiaGiam = 4,
		/// <summary>
		/// NgayTaoKhuyenMai : 
		/// </summary>
		[EnumTextValue("Ngay Tao Khuyen Mai")]
		[ColumnEnum("NgayTaoKhuyenMai", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		NgayTaoKhuyenMai = 5,
		/// <summary>
		/// NgayBatDauKhuyenMai : 
		/// </summary>
		[EnumTextValue("Ngay Bat Dau Khuyen Mai")]
		[ColumnEnum("NgayBatDauKhuyenMai", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		NgayBatDauKhuyenMai = 6,
		/// <summary>
		/// NgayKetThucKhuyenMai : 
		/// </summary>
		[EnumTextValue("Ngay Ket Thuc Khuyen Mai")]
		[ColumnEnum("NgayKetThucKhuyenMai", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		NgayKetThucKhuyenMai = 7,
		/// <summary>
		/// Active : 
		/// </summary>
		[EnumTextValue("Active")]
		[ColumnEnum("Active", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Active = 8
	}//End enum

	#endregion KhuyenMaiColumn Enum

} // end namespace
