
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file TinhTrangDa.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using SkinCare.Entities.Validation;
#endregion

namespace SkinCare.Entities
{
	///<summary>
	/// An object representation of the 'tblTinhTrangDa' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class TinhTrangDaBase : EntityBase, ITinhTrangDa, IEntityId<TinhTrangDaKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private TinhTrangDaEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private TinhTrangDaEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private TinhTrangDaEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<TinhTrangDa> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TinhTrangDaEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TinhTrangDaEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="TinhTrangDaBase"/> instance.
		///</summary>
		public TinhTrangDaBase()
		{
			this.entityData = new TinhTrangDaEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="TinhTrangDaBase"/> instance.
		///</summary>
		///<param name="_maKhachHang"></param>
		///<param name="_ngay"></param>
		///<param name="_tinhTrang"></param>
		public TinhTrangDaBase(System.Int32? _maKhachHang, System.DateTime? _ngay, System.String _tinhTrang)
		{
			this.entityData = new TinhTrangDaEntityData();
			this.backupData = null;

			this.MaKhachHang = _maKhachHang;
			this.Ngay = _ngay;
			this.TinhTrang = _tinhTrang;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="TinhTrangDa"/> instance.
		///</summary>
		///<param name="_maKhachHang"></param>
		///<param name="_ngay"></param>
		///<param name="_tinhTrang"></param>
		public static TinhTrangDa CreateTinhTrangDa(System.Int32? _maKhachHang, System.DateTime? _ngay, System.String _tinhTrang)
		{
			TinhTrangDa newTinhTrangDa = new TinhTrangDa();
			newTinhTrangDa.MaKhachHang = _maKhachHang;
			newTinhTrangDa.Ngay = _ngay;
			newTinhTrangDa.TinhTrang = _tinhTrang;
			return newTinhTrangDa;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(TinhTrangDaColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TinhTrangDaColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaKhachHang property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? MaKhachHang
		{
			get
			{
				return this.entityData.MaKhachHang; 
			}
			
			set
			{
				if (this.entityData.MaKhachHang == value)
					return;
				
                OnPropertyChanging("MaKhachHang");                    
				OnColumnChanging(TinhTrangDaColumn.MaKhachHang, this.entityData.MaKhachHang);
				this.entityData.MaKhachHang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TinhTrangDaColumn.MaKhachHang, this.entityData.MaKhachHang);
				OnPropertyChanged("MaKhachHang");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Ngay property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? Ngay
		{
			get
			{
				return this.entityData.Ngay; 
			}
			
			set
			{
				if (this.entityData.Ngay == value)
					return;
				
                OnPropertyChanging("Ngay");                    
				OnColumnChanging(TinhTrangDaColumn.Ngay, this.entityData.Ngay);
				this.entityData.Ngay = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TinhTrangDaColumn.Ngay, this.entityData.Ngay);
				OnPropertyChanged("Ngay");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TinhTrang property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String TinhTrang
		{
			get
			{
				return this.entityData.TinhTrang; 
			}
			
			set
			{
				if (this.entityData.TinhTrang == value)
					return;
				
                OnPropertyChanging("TinhTrang");                    
				OnColumnChanging(TinhTrangDaColumn.TinhTrang, this.entityData.TinhTrang);
				this.entityData.TinhTrang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TinhTrangDaColumn.TinhTrang, this.entityData.TinhTrang);
				OnPropertyChanged("TinhTrang");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TinhTrang", "Tinh Trang", 200));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblTinhTrangDa"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "MaKhachHang", "Ngay", "TinhTrang"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as TinhTrangDaEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (TinhTrangDa) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<TinhTrangDa>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as TinhTrangDa);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed TinhTrangDa Entity 
		///</summary>
		protected virtual TinhTrangDa Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			TinhTrangDa copy = new TinhTrangDa();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.MaKhachHang = this.MaKhachHang;
				copy.Ngay = this.Ngay;
				copy.TinhTrang = this.TinhTrang;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed TinhTrangDa Entity 
		///</summary>
		public virtual TinhTrangDa Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed TinhTrangDa Entity which is a deep copy of the current entity.
		///</summary>
		public virtual TinhTrangDa DeepCopy()
		{
			return EntityHelper.Clone<TinhTrangDa>(this as TinhTrangDa);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as TinhTrangDaEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new TinhTrangDaEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as TinhTrangDaEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(TinhTrangDaColumn column)
		{
			switch(column)
			{
					case TinhTrangDaColumn.Id:
					return entityData.Id != _originalData.Id;
					case TinhTrangDaColumn.MaKhachHang:
					return entityData.MaKhachHang != _originalData.MaKhachHang;
					case TinhTrangDaColumn.Ngay:
					return entityData.Ngay != _originalData.Ngay;
					case TinhTrangDaColumn.TinhTrang:
					return entityData.TinhTrang != _originalData.TinhTrang;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< TinhTrangDaColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.MaKhachHang != _originalData.MaKhachHang;
			result = result || entityData.Ngay != _originalData.Ngay;
			result = result || entityData.TinhTrang != _originalData.TinhTrang;
			return result;
		}	
		
		///<summary>
		///  Returns a TinhTrangDa Entity with the original data.
		///</summary>
		public TinhTrangDa GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateTinhTrangDa(
				_originalData.MaKhachHang,
				_originalData.Ngay,
				_originalData.TinhTrang
				);
				
			return (TinhTrangDa)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="TinhTrangDaBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is TinhTrangDaBase)
				return ValueEquals(this, (TinhTrangDaBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="TinhTrangDaBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.MaKhachHang == null) ? string.Empty : this.MaKhachHang.ToString()).GetHashCode() ^ 
					((this.Ngay == null) ? string.Empty : this.Ngay.ToString()).GetHashCode() ^ 
					((this.TinhTrang == null) ? string.Empty : this.TinhTrang.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="TinhTrangDaBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(TinhTrangDaBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="TinhTrangDaBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="TinhTrangDaBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="TinhTrangDaBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(TinhTrangDaBase Object1, TinhTrangDaBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.MaKhachHang != null && Object2.MaKhachHang != null )
			{
				if (Object1.MaKhachHang != Object2.MaKhachHang)
					equal = false;
			}
			else if (Object1.MaKhachHang == null ^ Object2.MaKhachHang == null )
			{
				equal = false;
			}
			if ( Object1.Ngay != null && Object2.Ngay != null )
			{
				if (Object1.Ngay != Object2.Ngay)
					equal = false;
			}
			else if (Object1.Ngay == null ^ Object2.Ngay == null )
			{
				equal = false;
			}
			if ( Object1.TinhTrang != null && Object2.TinhTrang != null )
			{
				if (Object1.TinhTrang != Object2.TinhTrang)
					equal = false;
			}
			else if (Object1.TinhTrang == null ^ Object2.TinhTrang == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((TinhTrangDaBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static TinhTrangDaComparer GetComparer()
        {
            return new TinhTrangDaComparer();
        }
        */

        // Comparer delegates back to TinhTrangDa
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(TinhTrangDa rhs, TinhTrangDaColumn which)
        {
            switch (which)
            {
            	
            	
            	case TinhTrangDaColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case TinhTrangDaColumn.MaKhachHang:
            		return this.MaKhachHang.Value.CompareTo(rhs.MaKhachHang.Value);
            		
            		                 
            	
            	
            	case TinhTrangDaColumn.Ngay:
            		return this.Ngay.Value.CompareTo(rhs.Ngay.Value);
            		
            		                 
            	
            	
            	case TinhTrangDaColumn.TinhTrang:
            		return this.TinhTrang.CompareTo(rhs.TinhTrang);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<TinhTrangDaKey> Members
		
		// member variable for the EntityId property
		private TinhTrangDaKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual TinhTrangDaKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new TinhTrangDaKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("TinhTrangDa")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- Id: {0}{4}- MaKhachHang: {1}{4}- Ngay: {2}{4}- TinhTrang: {3}{4}{6}", 
				this.Id,
				(this.MaKhachHang == null) ? string.Empty : this.MaKhachHang.ToString(),
				(this.Ngay == null) ? string.Empty : this.Ngay.ToString(),
				(this.TinhTrang == null) ? string.Empty : this.TinhTrang.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblTinhTrangDa' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class TinhTrangDaEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblTinhTrangDa"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaKhachHang : 
		/// </summary>
		public System.Int32? MaKhachHang = null;
		
		/// <summary>
		/// Ngay : 
		/// </summary>
		public System.DateTime? Ngay = null;
		
		/// <summary>
		/// TinhTrang : 
		/// </summary>
		public System.String TinhTrang = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			TinhTrangDaEntityData _tmp = new TinhTrangDaEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.MaKhachHang = this.MaKhachHang;
			_tmp.Ngay = this.Ngay;
			_tmp.TinhTrang = this.TinhTrang;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			TinhTrangDaEntityData _tmp = new TinhTrangDaEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.MaKhachHang = this.MaKhachHang;
			_tmp.Ngay = this.Ngay;
			_tmp.TinhTrang = this.TinhTrang;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TinhTrangDaColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(TinhTrangDaColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TinhTrangDaColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(TinhTrangDaColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TinhTrangDaColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(TinhTrangDaColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				TinhTrangDaEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new TinhTrangDaEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TinhTrangDaColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(TinhTrangDaColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				TinhTrangDaEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new TinhTrangDaEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region TinhTrangDaEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="TinhTrangDa"/> object.
	/// </remarks>
	public class TinhTrangDaEventArgs : System.EventArgs
	{
		private TinhTrangDaColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the TinhTrangDaEventArgs class.
		///</summary>
		public TinhTrangDaEventArgs(TinhTrangDaColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the TinhTrangDaEventArgs class.
		///</summary>
		public TinhTrangDaEventArgs(TinhTrangDaColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The TinhTrangDaColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="TinhTrangDaColumn" />
		public TinhTrangDaColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all TinhTrangDa related events.
	///</summary>
	public delegate void TinhTrangDaEventHandler(object sender, TinhTrangDaEventArgs e);
	
	#region TinhTrangDaComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class TinhTrangDaComparer : System.Collections.Generic.IComparer<TinhTrangDa>
	{
		TinhTrangDaColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:TinhTrangDaComparer"/> class.
        /// </summary>
		public TinhTrangDaComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:TinhTrangDaComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public TinhTrangDaComparer(TinhTrangDaColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="TinhTrangDa"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="TinhTrangDa"/> to compare.</param>
        /// <param name="b">The second <c>TinhTrangDa</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(TinhTrangDa a, TinhTrangDa b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(TinhTrangDa entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(TinhTrangDa a, TinhTrangDa b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public TinhTrangDaColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region TinhTrangDaKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="TinhTrangDa"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class TinhTrangDaKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the TinhTrangDaKey class.
		/// </summary>
		public TinhTrangDaKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the TinhTrangDaKey class.
		/// </summary>
		public TinhTrangDaKey(TinhTrangDaBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the TinhTrangDaKey class.
		/// </summary>
		public TinhTrangDaKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private TinhTrangDaBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public TinhTrangDaBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region TinhTrangDaColumn Enum
	
	/// <summary>
	/// Enumerate the TinhTrangDa columns.
	/// </summary>
	[Serializable]
	public enum TinhTrangDaColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// MaKhachHang : 
		/// </summary>
		[EnumTextValue("Ma Khach Hang")]
		[ColumnEnum("MaKhachHang", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		MaKhachHang = 2,
		/// <summary>
		/// Ngay : 
		/// </summary>
		[EnumTextValue("Ngay")]
		[ColumnEnum("Ngay", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		Ngay = 3,
		/// <summary>
		/// TinhTrang : 
		/// </summary>
		[EnumTextValue("Tinh Trang")]
		[ColumnEnum("TinhTrang", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		TinhTrang = 4
	}//End enum

	#endregion TinhTrangDaColumn Enum

} // end namespace
