
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file TrangThaiDonHang.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using SkinCare.Entities.Validation;
#endregion

namespace SkinCare.Entities
{
	///<summary>
	/// An object representation of the 'tblTrangThaiDonHang' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class TrangThaiDonHangBase : EntityBase, ITrangThaiDonHang, IEntityId<TrangThaiDonHangKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private TrangThaiDonHangEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private TrangThaiDonHangEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private TrangThaiDonHangEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<TrangThaiDonHang> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TrangThaiDonHangEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TrangThaiDonHangEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="TrangThaiDonHangBase"/> instance.
		///</summary>
		public TrangThaiDonHangBase()
		{
			this.entityData = new TrangThaiDonHangEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="TrangThaiDonHangBase"/> instance.
		///</summary>
		///<param name="_maTrangThaiDonHang"></param>
		///<param name="_maLoaiTrangThaiDonHang"></param>
		///<param name="_tenLoaiTrangThaiDonHang">Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room</param>
		public TrangThaiDonHangBase(System.Int32 _maTrangThaiDonHang, System.Int32 _maLoaiTrangThaiDonHang, 
			System.String _tenLoaiTrangThaiDonHang)
		{
			this.entityData = new TrangThaiDonHangEntityData();
			this.backupData = null;

			this.MaTrangThaiDonHang = _maTrangThaiDonHang;
			this.MaLoaiTrangThaiDonHang = _maLoaiTrangThaiDonHang;
			this.TenLoaiTrangThaiDonHang = _tenLoaiTrangThaiDonHang;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="TrangThaiDonHang"/> instance.
		///</summary>
		///<param name="_maTrangThaiDonHang"></param>
		///<param name="_maLoaiTrangThaiDonHang"></param>
		///<param name="_tenLoaiTrangThaiDonHang">Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room</param>
		public static TrangThaiDonHang CreateTrangThaiDonHang(System.Int32 _maTrangThaiDonHang, System.Int32 _maLoaiTrangThaiDonHang, 
			System.String _tenLoaiTrangThaiDonHang)
		{
			TrangThaiDonHang newTrangThaiDonHang = new TrangThaiDonHang();
			newTrangThaiDonHang.MaTrangThaiDonHang = _maTrangThaiDonHang;
			newTrangThaiDonHang.MaLoaiTrangThaiDonHang = _maLoaiTrangThaiDonHang;
			newTrangThaiDonHang.TenLoaiTrangThaiDonHang = _tenLoaiTrangThaiDonHang;
			return newTrangThaiDonHang;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaTrangThaiDonHang property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 MaTrangThaiDonHang
		{
			get
			{
				return this.entityData.MaTrangThaiDonHang; 
			}
			
			set
			{
				if (this.entityData.MaTrangThaiDonHang == value)
					return;
				
                OnPropertyChanging("MaTrangThaiDonHang");                    
				OnColumnChanging(TrangThaiDonHangColumn.MaTrangThaiDonHang, this.entityData.MaTrangThaiDonHang);
				this.entityData.MaTrangThaiDonHang = value;
				this.EntityId.MaTrangThaiDonHang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrangThaiDonHangColumn.MaTrangThaiDonHang, this.entityData.MaTrangThaiDonHang);
				OnPropertyChanged("MaTrangThaiDonHang");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MaTrangThaiDonHang property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MaTrangThaiDonHang property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalMaTrangThaiDonHang
		{
			get { return this.entityData.OriginalMaTrangThaiDonHang; }
			set { this.entityData.OriginalMaTrangThaiDonHang = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the MaLoaiTrangThaiDonHang property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 MaLoaiTrangThaiDonHang
		{
			get
			{
				return this.entityData.MaLoaiTrangThaiDonHang; 
			}
			
			set
			{
				if (this.entityData.MaLoaiTrangThaiDonHang == value)
					return;
				
                OnPropertyChanging("MaLoaiTrangThaiDonHang");                    
				OnColumnChanging(TrangThaiDonHangColumn.MaLoaiTrangThaiDonHang, this.entityData.MaLoaiTrangThaiDonHang);
				this.entityData.MaLoaiTrangThaiDonHang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrangThaiDonHangColumn.MaLoaiTrangThaiDonHang, this.entityData.MaLoaiTrangThaiDonHang);
				OnPropertyChanged("MaLoaiTrangThaiDonHang");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenLoaiTrangThaiDonHang property. 
		///		Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String TenLoaiTrangThaiDonHang
		{
			get
			{
				return this.entityData.TenLoaiTrangThaiDonHang; 
			}
			
			set
			{
				if (this.entityData.TenLoaiTrangThaiDonHang == value)
					return;
				
                OnPropertyChanging("TenLoaiTrangThaiDonHang");                    
				OnColumnChanging(TrangThaiDonHangColumn.TenLoaiTrangThaiDonHang, this.entityData.TenLoaiTrangThaiDonHang);
				this.entityData.TenLoaiTrangThaiDonHang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrangThaiDonHangColumn.TenLoaiTrangThaiDonHang, this.entityData.TenLoaiTrangThaiDonHang);
				OnPropertyChanged("TenLoaiTrangThaiDonHang");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TenLoaiTrangThaiDonHang", "Ten Loai Trang Thai Don Hang", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblTrangThaiDonHang"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaTrangThaiDonHang", "MaLoaiTrangThaiDonHang", "TenLoaiTrangThaiDonHang"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as TrangThaiDonHangEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (TrangThaiDonHang) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<TrangThaiDonHang>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as TrangThaiDonHang);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed TrangThaiDonHang Entity 
		///</summary>
		protected virtual TrangThaiDonHang Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			TrangThaiDonHang copy = new TrangThaiDonHang();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MaTrangThaiDonHang = this.MaTrangThaiDonHang;
					copy.OriginalMaTrangThaiDonHang = this.OriginalMaTrangThaiDonHang;
				copy.MaLoaiTrangThaiDonHang = this.MaLoaiTrangThaiDonHang;
				copy.TenLoaiTrangThaiDonHang = this.TenLoaiTrangThaiDonHang;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed TrangThaiDonHang Entity 
		///</summary>
		public virtual TrangThaiDonHang Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed TrangThaiDonHang Entity which is a deep copy of the current entity.
		///</summary>
		public virtual TrangThaiDonHang DeepCopy()
		{
			return EntityHelper.Clone<TrangThaiDonHang>(this as TrangThaiDonHang);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as TrangThaiDonHangEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new TrangThaiDonHangEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as TrangThaiDonHangEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(TrangThaiDonHangColumn column)
		{
			switch(column)
			{
					case TrangThaiDonHangColumn.MaTrangThaiDonHang:
					return entityData.MaTrangThaiDonHang != _originalData.MaTrangThaiDonHang;
					case TrangThaiDonHangColumn.MaLoaiTrangThaiDonHang:
					return entityData.MaLoaiTrangThaiDonHang != _originalData.MaLoaiTrangThaiDonHang;
					case TrangThaiDonHangColumn.TenLoaiTrangThaiDonHang:
					return entityData.TenLoaiTrangThaiDonHang != _originalData.TenLoaiTrangThaiDonHang;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< TrangThaiDonHangColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaTrangThaiDonHang != _originalData.MaTrangThaiDonHang;
			result = result || entityData.MaLoaiTrangThaiDonHang != _originalData.MaLoaiTrangThaiDonHang;
			result = result || entityData.TenLoaiTrangThaiDonHang != _originalData.TenLoaiTrangThaiDonHang;
			return result;
		}	
		
		///<summary>
		///  Returns a TrangThaiDonHang Entity with the original data.
		///</summary>
		public TrangThaiDonHang GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateTrangThaiDonHang(
				_originalData.MaTrangThaiDonHang,
				_originalData.MaLoaiTrangThaiDonHang,
				_originalData.TenLoaiTrangThaiDonHang
				);
				
			return (TrangThaiDonHang)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="TrangThaiDonHangBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is TrangThaiDonHangBase)
				return ValueEquals(this, (TrangThaiDonHangBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="TrangThaiDonHangBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaTrangThaiDonHang.GetHashCode() ^ 
					this.MaLoaiTrangThaiDonHang.GetHashCode() ^ 
					((this.TenLoaiTrangThaiDonHang == null) ? string.Empty : this.TenLoaiTrangThaiDonHang.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="TrangThaiDonHangBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(TrangThaiDonHangBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="TrangThaiDonHangBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="TrangThaiDonHangBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="TrangThaiDonHangBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(TrangThaiDonHangBase Object1, TrangThaiDonHangBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaTrangThaiDonHang != Object2.MaTrangThaiDonHang)
				equal = false;
			if (Object1.MaLoaiTrangThaiDonHang != Object2.MaLoaiTrangThaiDonHang)
				equal = false;
			if ( Object1.TenLoaiTrangThaiDonHang != null && Object2.TenLoaiTrangThaiDonHang != null )
			{
				if (Object1.TenLoaiTrangThaiDonHang != Object2.TenLoaiTrangThaiDonHang)
					equal = false;
			}
			else if (Object1.TenLoaiTrangThaiDonHang == null ^ Object2.TenLoaiTrangThaiDonHang == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((TrangThaiDonHangBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static TrangThaiDonHangComparer GetComparer()
        {
            return new TrangThaiDonHangComparer();
        }
        */

        // Comparer delegates back to TrangThaiDonHang
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(TrangThaiDonHang rhs, TrangThaiDonHangColumn which)
        {
            switch (which)
            {
            	
            	
            	case TrangThaiDonHangColumn.MaTrangThaiDonHang:
            		return this.MaTrangThaiDonHang.CompareTo(rhs.MaTrangThaiDonHang);
            		
            		                 
            	
            	
            	case TrangThaiDonHangColumn.MaLoaiTrangThaiDonHang:
            		return this.MaLoaiTrangThaiDonHang.CompareTo(rhs.MaLoaiTrangThaiDonHang);
            		
            		                 
            	
            	
            	case TrangThaiDonHangColumn.TenLoaiTrangThaiDonHang:
            		return this.TenLoaiTrangThaiDonHang.CompareTo(rhs.TenLoaiTrangThaiDonHang);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<TrangThaiDonHangKey> Members
		
		// member variable for the EntityId property
		private TrangThaiDonHangKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual TrangThaiDonHangKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new TrangThaiDonHangKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("TrangThaiDonHang")
					.Append("|").Append( this.MaTrangThaiDonHang.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- MaTrangThaiDonHang: {0}{3}- MaLoaiTrangThaiDonHang: {1}{3}- TenLoaiTrangThaiDonHang: {2}{3}{5}", 
				this.MaTrangThaiDonHang,
				this.MaLoaiTrangThaiDonHang,
				(this.TenLoaiTrangThaiDonHang == null) ? string.Empty : this.TenLoaiTrangThaiDonHang.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblTrangThaiDonHang' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class TrangThaiDonHangEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MaTrangThaiDonHang : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblTrangThaiDonHang"</remarks>
		public System.Int32 MaTrangThaiDonHang;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalMaTrangThaiDonHang;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaLoaiTrangThaiDonHang : 
		/// </summary>
		public System.Int32 MaLoaiTrangThaiDonHang = (int)0;
		
		/// <summary>
		/// TenLoaiTrangThaiDonHang : Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room
		/// </summary>
		public System.String TenLoaiTrangThaiDonHang = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			TrangThaiDonHangEntityData _tmp = new TrangThaiDonHangEntityData();
						
			_tmp.MaTrangThaiDonHang = this.MaTrangThaiDonHang;
			_tmp.OriginalMaTrangThaiDonHang = this.OriginalMaTrangThaiDonHang;
			
			_tmp.MaLoaiTrangThaiDonHang = this.MaLoaiTrangThaiDonHang;
			_tmp.TenLoaiTrangThaiDonHang = this.TenLoaiTrangThaiDonHang;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			TrangThaiDonHangEntityData _tmp = new TrangThaiDonHangEntityData();
						
			_tmp.MaTrangThaiDonHang = this.MaTrangThaiDonHang;
			_tmp.OriginalMaTrangThaiDonHang = this.OriginalMaTrangThaiDonHang;
			
			_tmp.MaLoaiTrangThaiDonHang = this.MaLoaiTrangThaiDonHang;
			_tmp.TenLoaiTrangThaiDonHang = this.TenLoaiTrangThaiDonHang;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrangThaiDonHangColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(TrangThaiDonHangColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrangThaiDonHangColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(TrangThaiDonHangColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrangThaiDonHangColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(TrangThaiDonHangColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				TrangThaiDonHangEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new TrangThaiDonHangEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrangThaiDonHangColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(TrangThaiDonHangColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				TrangThaiDonHangEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new TrangThaiDonHangEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region TrangThaiDonHangEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="TrangThaiDonHang"/> object.
	/// </remarks>
	public class TrangThaiDonHangEventArgs : System.EventArgs
	{
		private TrangThaiDonHangColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the TrangThaiDonHangEventArgs class.
		///</summary>
		public TrangThaiDonHangEventArgs(TrangThaiDonHangColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the TrangThaiDonHangEventArgs class.
		///</summary>
		public TrangThaiDonHangEventArgs(TrangThaiDonHangColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The TrangThaiDonHangColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="TrangThaiDonHangColumn" />
		public TrangThaiDonHangColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all TrangThaiDonHang related events.
	///</summary>
	public delegate void TrangThaiDonHangEventHandler(object sender, TrangThaiDonHangEventArgs e);
	
	#region TrangThaiDonHangComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class TrangThaiDonHangComparer : System.Collections.Generic.IComparer<TrangThaiDonHang>
	{
		TrangThaiDonHangColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:TrangThaiDonHangComparer"/> class.
        /// </summary>
		public TrangThaiDonHangComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:TrangThaiDonHangComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public TrangThaiDonHangComparer(TrangThaiDonHangColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="TrangThaiDonHang"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="TrangThaiDonHang"/> to compare.</param>
        /// <param name="b">The second <c>TrangThaiDonHang</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(TrangThaiDonHang a, TrangThaiDonHang b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(TrangThaiDonHang entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(TrangThaiDonHang a, TrangThaiDonHang b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public TrangThaiDonHangColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region TrangThaiDonHangKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="TrangThaiDonHang"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class TrangThaiDonHangKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the TrangThaiDonHangKey class.
		/// </summary>
		public TrangThaiDonHangKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the TrangThaiDonHangKey class.
		/// </summary>
		public TrangThaiDonHangKey(TrangThaiDonHangBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaTrangThaiDonHang = entity.MaTrangThaiDonHang;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the TrangThaiDonHangKey class.
		/// </summary>
		public TrangThaiDonHangKey(System.Int32 _maTrangThaiDonHang)
		{
			#region Init Properties

			this.MaTrangThaiDonHang = _maTrangThaiDonHang;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private TrangThaiDonHangBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public TrangThaiDonHangBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaTrangThaiDonHang property
		private System.Int32 _maTrangThaiDonHang;
		
		/// <summary>
		/// Gets or sets the MaTrangThaiDonHang property.
		/// </summary>
		public System.Int32 MaTrangThaiDonHang
		{
			get { return _maTrangThaiDonHang; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaTrangThaiDonHang = value;
				
				_maTrangThaiDonHang = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaTrangThaiDonHang = ( values["MaTrangThaiDonHang"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MaTrangThaiDonHang"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaTrangThaiDonHang", MaTrangThaiDonHang);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaTrangThaiDonHang: {0}{1}",
								MaTrangThaiDonHang,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region TrangThaiDonHangColumn Enum
	
	/// <summary>
	/// Enumerate the TrangThaiDonHang columns.
	/// </summary>
	[Serializable]
	public enum TrangThaiDonHangColumn : int
	{
		/// <summary>
		/// MaTrangThaiDonHang : 
		/// </summary>
		[EnumTextValue("Ma Trang Thai Don Hang")]
		[ColumnEnum("MaTrangThaiDonHang", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		MaTrangThaiDonHang = 1,
		/// <summary>
		/// MaLoaiTrangThaiDonHang : 
		/// </summary>
		[EnumTextValue("Ma Loai Trang Thai Don Hang")]
		[ColumnEnum("MaLoaiTrangThaiDonHang", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		MaLoaiTrangThaiDonHang = 2,
		/// <summary>
		/// TenLoaiTrangThaiDonHang : Kho - xuat hang EMS | Kho - xuat hang NV | Kho - Dang Giao Hang | TV - Xuat hang show room | Kho - Da Giao Hang COD | TV - Da giao thu tien mat | TV - Da giao chuyen khoan | TV - Da giao hang POS | ---- Su co cho chuyen khoan | ---- Su co thong tin khach hang | ---- Su co Hang chuyen khoan | ---- Su co Kho thieu hang | Khoi Tao | Khoi tao - Chua thanh toan | Khoi tao - Thanh Toan thanh cong | Khoi tao - Loi Thanh Toan | Xu ly | Kho Xu Ly | TV- Xac nhan | Cho Nhan Hang show room or Kho - xuat hang NV or Kho - Dang Giao Hang or TV - Xuat hang show room or Kho - Da Giao Hang COD or TV - Da giao thu tien mat or TV - Da giao chuyen khoan or TV - Da giao hang POS or ---- Su co cho chuyen khoan or ---- Su co thong tin khach hang or ---- Su co Hang chuyen khoan or ---- Su co Kho thieu hang or Khoi Tao or Khoi tao - Chua thanh toan or Khoi tao - Thanh Toan thanh cong or Khoi tao - Loi Thanh Toan or Xu ly or Kho Xu Ly or TV- Xac nhan or Cho Nhan Hang show room
		/// </summary>
		[EnumTextValue("Ten Loai Trang Thai Don Hang")]
		[ColumnEnum("TenLoaiTrangThaiDonHang", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		TenLoaiTrangThaiDonHang = 3
	}//End enum

	#endregion TrangThaiDonHangColumn Enum

} // end namespace
