/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file SqlDonHangProvider.cs instead.
*/

#region using directives

using System;
using System.Data;
using System.Data.Common;
using System.Text;

using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;

using System.Collections;
using System.Collections.Specialized;

using System.Diagnostics;
using SkinCare.Entities;
using SkinCare.Data;
using SkinCare.Data.Bases;

#endregion

namespace SkinCare.Data.SqlClient
{
	///<summary>
	/// This class is the SqlClient Data Access Logic Component implementation for the <see cref="DonHang"/> entity.
	///</summary>
	public abstract partial class SqlDonHangProviderBase : DonHangProviderBase
	{
		#region Declarations
		
		string _connectionString;
	    bool _useStoredProcedure;
	    string _providerInvariantName;
			
		#endregion "Declarations"
			
		#region Constructors
		
		/// <summary>
		/// Creates a new <see cref="SqlDonHangProviderBase"/> instance.
		/// </summary>
		public SqlDonHangProviderBase()
		{
		}
	
	/// <summary>
	/// Creates a new <see cref="SqlDonHangProviderBase"/> instance.
	/// Uses connection string to connect to datasource.
	/// </summary>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="useStoredProcedure">A boolean value that indicates if we should use stored procedures or embedded queries.</param>
	/// <param name="providerInvariantName">Name of the invariant provider use by the DbProviderFactory.</param>
	public SqlDonHangProviderBase(string connectionString, bool useStoredProcedure, string providerInvariantName)
	{
		this._connectionString = connectionString;
		this._useStoredProcedure = useStoredProcedure;
		this._providerInvariantName = providerInvariantName;
	}
		
	#endregion "Constructors"
	
		#region Public properties
	/// <summary>
    /// Gets or sets the connection string.
    /// </summary>
    /// <value>The connection string.</value>
    public string ConnectionString
	{
		get {return this._connectionString;}
		set {this._connectionString = value;}
	}
	
	/// <summary>
    /// Gets or sets a value indicating whether to use stored procedures.
    /// </summary>
    /// <value><c>true</c> if we choose to use use stored procedures; otherwise, <c>false</c>.</value>
	public bool UseStoredProcedure
	{
		get {return this._useStoredProcedure;}
		set {this._useStoredProcedure = value;}
	}
	
	/// <summary>
    /// Gets or sets the invariant provider name listed in the DbProviderFactories machine.config section.
    /// </summary>
    /// <value>The name of the provider invariant.</value>
    public string ProviderInvariantName
    {
        get { return this._providerInvariantName; }
        set { this._providerInvariantName = value; }
    }
	#endregion
	
		#region Get Many To Many Relationship Functions
		#endregion
	
		#region Delete Functions
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="_maDonHang">. Primary Key.</param>	
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Delete(TransactionManager transactionManager, System.Int32 _maDonHang)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_Delete", _useStoredProcedure);
			database.AddInParameter(commandWrapper, "@MaDonHang", DbType.Int32, _maDonHang);
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Delete")); 

			int results = 0;
			
			if (transactionManager != null)
			{	
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
			{
				string entityKey = EntityLocator.ConstructKeyFromPkItems(typeof(DonHang)
					,_maDonHang);
                EntityManager.StopTracking(entityKey);
                
			}
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Delete")); 

			commandWrapper = null;
			
			return Convert.ToBoolean(results);
		}//end Delete
		#endregion

		#region Find Functions

		#region Parsed Find Methods
		/// <summary>
		/// 	Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks>Operators must be capitalized (OR, AND).</remarks>
		/// <returns>Returns a typed collection of SkinCare.Entities.DonHang objects.</returns>
		public override TList<DonHang> Find(TransactionManager transactionManager, string whereClause, int start, int pageLength, out int count)
		{
			count = -1;
			if (whereClause.IndexOf(";") > -1)
				return new TList<DonHang>();
	
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_Find", _useStoredProcedure);

		bool searchUsingOR = false;
		if (whereClause.IndexOf(" OR ") > 0) // did they want to do "a=b OR c=d OR..."?
			searchUsingOR = true;
		
		database.AddInParameter(commandWrapper, "@SearchUsingOR", DbType.Boolean, searchUsingOR);
		
		database.AddInParameter(commandWrapper, "@MaDonHang", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaNguonDonHang", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaTrangThaiDonHang", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@NguoiDatHang", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaPhuongThucThanhToan", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@CachThucNhanHang", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@PhiVanChuyen", DbType.Decimal, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TongTienDonHang", DbType.Decimal, DBNull.Value);
		database.AddInParameter(commandWrapper, "@NgayTaoDonHang", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaKhuyenMai", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaVoucher", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@GhiChu", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TienChietKhau", DbType.Decimal, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TiLeChietKhau", DbType.Double, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsDeleted", DbType.Boolean, DBNull.Value);
	
			// replace all instances of 'AND' and 'OR' because we already set searchUsingOR
			whereClause = whereClause.Replace(" AND ", "|").Replace(" OR ", "|") ; 
			string[] clauses = whereClause.ToLower().Split('|');
		
			// Here's what's going on below: Find a field, then to get the value we
			// drop the field name from the front, trim spaces, drop the '=' sign,
			// trim more spaces, and drop any outer single quotes.
			// Now handles the case when two fields start off the same way - like "Friendly='Yes' AND Friend='john'"
				
			char[] equalSign = {'='};
			char[] singleQuote = {'\''};
	   		foreach (string clause in clauses)
			{
				if (clause.Trim().StartsWith("madonhang ") || clause.Trim().StartsWith("madonhang="))
				{
					database.SetParameterValue(commandWrapper, "@MaDonHang", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("makhachhang ") || clause.Trim().StartsWith("makhachhang="))
				{
					database.SetParameterValue(commandWrapper, "@MaKhachHang", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("manguondonhang ") || clause.Trim().StartsWith("manguondonhang="))
				{
					database.SetParameterValue(commandWrapper, "@MaNguonDonHang", 
						clause.Trim().Remove(0,14).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("matrangthaidonhang ") || clause.Trim().StartsWith("matrangthaidonhang="))
				{
					database.SetParameterValue(commandWrapper, "@MaTrangThaiDonHang", 
						clause.Trim().Remove(0,18).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("nguoidathang ") || clause.Trim().StartsWith("nguoidathang="))
				{
					database.SetParameterValue(commandWrapper, "@NguoiDatHang", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("maphuongthucthanhtoan ") || clause.Trim().StartsWith("maphuongthucthanhtoan="))
				{
					database.SetParameterValue(commandWrapper, "@MaPhuongThucThanhToan", 
						clause.Trim().Remove(0,21).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("cachthucnhanhang ") || clause.Trim().StartsWith("cachthucnhanhang="))
				{
					database.SetParameterValue(commandWrapper, "@CachThucNhanHang", 
						clause.Trim().Remove(0,16).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("phivanchuyen ") || clause.Trim().StartsWith("phivanchuyen="))
				{
					database.SetParameterValue(commandWrapper, "@PhiVanChuyen", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tongtiendonhang ") || clause.Trim().StartsWith("tongtiendonhang="))
				{
					database.SetParameterValue(commandWrapper, "@TongTienDonHang", 
						clause.Trim().Remove(0,15).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ngaytaodonhang ") || clause.Trim().StartsWith("ngaytaodonhang="))
				{
					database.SetParameterValue(commandWrapper, "@NgayTaoDonHang", 
						clause.Trim().Remove(0,14).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("makhuyenmai ") || clause.Trim().StartsWith("makhuyenmai="))
				{
					database.SetParameterValue(commandWrapper, "@MaKhuyenMai", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("mavoucher ") || clause.Trim().StartsWith("mavoucher="))
				{
					database.SetParameterValue(commandWrapper, "@MaVoucher", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ghichu ") || clause.Trim().StartsWith("ghichu="))
				{
					database.SetParameterValue(commandWrapper, "@GhiChu", 
						clause.Trim().Remove(0,6).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tienchietkhau ") || clause.Trim().StartsWith("tienchietkhau="))
				{
					database.SetParameterValue(commandWrapper, "@TienChietKhau", 
						clause.Trim().Remove(0,13).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tilechietkhau ") || clause.Trim().StartsWith("tilechietkhau="))
				{
					database.SetParameterValue(commandWrapper, "@TiLeChietKhau", 
						clause.Trim().Remove(0,13).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isdeleted ") || clause.Trim().StartsWith("isdeleted="))
				{
					database.SetParameterValue(commandWrapper, "@IsDeleted", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
	
				throw new ArgumentException("Unable to use this part of the where clause in this version of Find: " + clause);
			}
					
			IDataReader reader = null;
			//Create Collection
			TList<DonHang> rows = new TList<DonHang>();
	
				
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
				
				Fill(reader, rows, start, pageLength);
				
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if (reader != null) 
					reader.Close();	
					
				commandWrapper = null;
			}
			return rows;
		}

		#endregion Parsed Find Methods
		
		#region Parameterized Find Methods
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of SkinCare.Entities.DonHang objects.</returns>
		public override TList<DonHang> Find(TransactionManager transactionManager, IFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			SqlFilterParameterCollection filter = null;
			
			if (parameters == null)
				filter = new SqlFilterParameterCollection();
			else 
				filter = parameters.GetParameters();
				
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_Find_Dynamic", typeof(DonHangColumn), filter, orderBy, start, pageLength);
		
			SqlFilterParameter param;

			for ( int i = 0; i < filter.Count; i++ )
			{
				param = filter[i];
				database.AddInParameter(commandWrapper, param.Name, param.DbType, param.GetValue());
			}

			TList<DonHang> rows = new TList<DonHang>();
			IDataReader reader = null;
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if ( transactionManager != null )
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;
				
				if ( reader.NextResult() )
				{
					if ( reader.Read() )
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if ( reader != null )
					reader.Close();
					
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion Parameterized Find Methods
		
		#endregion Find Functions
	
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of SkinCare.Entities.DonHang objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override TList<DonHang> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_Get_List", _useStoredProcedure);
			
			IDataReader reader = null;
		
			//Create Collection
			TList<DonHang> rows = new TList<DonHang>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
					
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;	
			}
			return rows;
		}//end getall
		
		#endregion
				
		#region GetPaged Methods
				
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of SkinCare.Entities.DonHang objects.</returns>
		public override TList<DonHang> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_GetPaged", _useStoredProcedure);
		
			
            if (commandWrapper.CommandType == CommandType.Text
                && commandWrapper.CommandText != null)
            {
                commandWrapper.CommandText = commandWrapper.CommandText.Replace(SqlUtil.PAGE_INDEX, string.Concat(SqlUtil.PAGE_INDEX, Guid.NewGuid().ToString("N").Substring(0, 8)));
            }
			
			database.AddInParameter(commandWrapper, "@WhereClause", DbType.String, whereClause);
			database.AddInParameter(commandWrapper, "@OrderBy", DbType.String, orderBy);
			database.AddInParameter(commandWrapper, "@PageIndex", DbType.Int32, start);
			database.AddInParameter(commandWrapper, "@PageSize", DbType.Int32, pageLength);
		
			IDataReader reader = null;
			//Create Collection
			TList<DonHang> rows = new TList<DonHang>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;

				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

			}
			catch(Exception)
			{			
				throw;
			}
			finally
			{
				if (reader != null) 
					reader.Close();
				
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion	
		
		#region Get By Foreign Key Functions
	#endregion
	
		#region Get By Index Functions

		#region GetByMaDonHang
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_tblDonHang index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_maDonHang"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query.</param>
		/// <returns>Returns an instance of the <see cref="SkinCare.Entities.DonHang"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override SkinCare.Entities.DonHang GetByMaDonHang(TransactionManager transactionManager, System.Int32 _maDonHang, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_GetByMaDonHang", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@MaDonHang", DbType.Int32, _maDonHang);
			
			IDataReader reader = null;
			TList<DonHang> tmp = new TList<DonHang>();
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetByMaDonHang", tmp)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetByMaDonHang", tmp));
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;
			}
			
			if (tmp.Count == 1)
			{
				return tmp[0];
			}
			else if (tmp.Count == 0)
			{
				return null;
			}
			else
			{
				throw new DataException("Cannot find the unique instance of the class.");
			}
			
			//return rows;
		}
		
		#endregion

	#endregion Get By Index Functions

		#region Insert Methods
		/// <summary>
		/// Lets you efficiently bulk insert many entities to the database.
		/// </summary>
		/// <param name="transactionManager">The transaction manager.</param>
		/// <param name="entities">The entities.</param>
		/// <remarks>
		///		After inserting into the datasource, the SkinCare.Entities.DonHang object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		public override void BulkInsert(TransactionManager transactionManager, TList<SkinCare.Entities.DonHang> entities)
		{
			//System.Data.SqlClient.SqlBulkCopy bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			
			System.Data.SqlClient.SqlBulkCopy bulkCopy = null;
	
			if (transactionManager != null && transactionManager.IsOpen)
			{			
				System.Data.SqlClient.SqlConnection cnx = transactionManager.TransactionObject.Connection as System.Data.SqlClient.SqlConnection;
				System.Data.SqlClient.SqlTransaction transaction = transactionManager.TransactionObject as System.Data.SqlClient.SqlTransaction;
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, transaction); //, null);
			}
			else
			{
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			}
			
			bulkCopy.BulkCopyTimeout = 360;
			bulkCopy.DestinationTableName = "tblDonHang";
			
			DataTable dataTable = new DataTable();
			DataColumn col0 = dataTable.Columns.Add("MaDonHang", typeof(System.Int32));
			col0.AllowDBNull = false;		
			DataColumn col1 = dataTable.Columns.Add("MaKhachHang", typeof(System.Int32));
			col1.AllowDBNull = true;		
			DataColumn col2 = dataTable.Columns.Add("MaNguonDonHang", typeof(System.Int32));
			col2.AllowDBNull = true;		
			DataColumn col3 = dataTable.Columns.Add("MaTrangThaiDonHang", typeof(System.Int32));
			col3.AllowDBNull = true;		
			DataColumn col4 = dataTable.Columns.Add("NguoiDatHang", typeof(System.String));
			col4.AllowDBNull = true;		
			DataColumn col5 = dataTable.Columns.Add("MaPhuongThucThanhToan", typeof(System.Int32));
			col5.AllowDBNull = true;		
			DataColumn col6 = dataTable.Columns.Add("CachThucNhanHang", typeof(System.String));
			col6.AllowDBNull = true;		
			DataColumn col7 = dataTable.Columns.Add("PhiVanChuyen", typeof(System.Decimal));
			col7.AllowDBNull = true;		
			DataColumn col8 = dataTable.Columns.Add("TongTienDonHang", typeof(System.Decimal));
			col8.AllowDBNull = true;		
			DataColumn col9 = dataTable.Columns.Add("NgayTaoDonHang", typeof(System.DateTime));
			col9.AllowDBNull = true;		
			DataColumn col10 = dataTable.Columns.Add("MaKhuyenMai", typeof(System.String));
			col10.AllowDBNull = true;		
			DataColumn col11 = dataTable.Columns.Add("MaVoucher", typeof(System.String));
			col11.AllowDBNull = true;		
			DataColumn col12 = dataTable.Columns.Add("GhiChu", typeof(System.String));
			col12.AllowDBNull = true;		
			DataColumn col13 = dataTable.Columns.Add("TienChietKhau", typeof(System.Decimal));
			col13.AllowDBNull = true;		
			DataColumn col14 = dataTable.Columns.Add("TiLeChietKhau", typeof(System.Double));
			col14.AllowDBNull = true;		
			DataColumn col15 = dataTable.Columns.Add("IsDeleted", typeof(System.Boolean));
			col15.AllowDBNull = false;		
			
			bulkCopy.ColumnMappings.Add("MaDonHang", "MaDonHang");
			bulkCopy.ColumnMappings.Add("MaKhachHang", "MaKhachHang");
			bulkCopy.ColumnMappings.Add("MaNguonDonHang", "MaNguonDonHang");
			bulkCopy.ColumnMappings.Add("MaTrangThaiDonHang", "MaTrangThaiDonHang");
			bulkCopy.ColumnMappings.Add("NguoiDatHang", "NguoiDatHang");
			bulkCopy.ColumnMappings.Add("MaPhuongThucThanhToan", "MaPhuongThucThanhToan");
			bulkCopy.ColumnMappings.Add("CachThucNhanHang", "CachThucNhanHang");
			bulkCopy.ColumnMappings.Add("PhiVanChuyen", "PhiVanChuyen");
			bulkCopy.ColumnMappings.Add("TongTienDonHang", "TongTienDonHang");
			bulkCopy.ColumnMappings.Add("NgayTaoDonHang", "NgayTaoDonHang");
			bulkCopy.ColumnMappings.Add("MaKhuyenMai", "MaKhuyenMai");
			bulkCopy.ColumnMappings.Add("MaVoucher", "MaVoucher");
			bulkCopy.ColumnMappings.Add("GhiChu", "GhiChu");
			bulkCopy.ColumnMappings.Add("TienChietKhau", "TienChietKhau");
			bulkCopy.ColumnMappings.Add("TiLeChietKhau", "TiLeChietKhau");
			bulkCopy.ColumnMappings.Add("IsDeleted", "IsDeleted");
			
			foreach(SkinCare.Entities.DonHang entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
					
				DataRow row = dataTable.NewRow();
				
					row["MaDonHang"] = entity.MaDonHang;
							
				
					row["MaKhachHang"] = entity.MaKhachHang.HasValue ? (object) entity.MaKhachHang  : System.DBNull.Value;
							
				
					row["MaNguonDonHang"] = entity.MaNguonDonHang.HasValue ? (object) entity.MaNguonDonHang  : System.DBNull.Value;
							
				
					row["MaTrangThaiDonHang"] = entity.MaTrangThaiDonHang.HasValue ? (object) entity.MaTrangThaiDonHang  : System.DBNull.Value;
							
				
					row["NguoiDatHang"] = entity.NguoiDatHang;
							
				
					row["MaPhuongThucThanhToan"] = entity.MaPhuongThucThanhToan.HasValue ? (object) entity.MaPhuongThucThanhToan  : System.DBNull.Value;
							
				
					row["CachThucNhanHang"] = entity.CachThucNhanHang;
							
				
					row["PhiVanChuyen"] = entity.PhiVanChuyen.HasValue ? (object) entity.PhiVanChuyen  : System.DBNull.Value;
							
				
					row["TongTienDonHang"] = entity.TongTienDonHang.HasValue ? (object) entity.TongTienDonHang  : System.DBNull.Value;
							
				
					row["NgayTaoDonHang"] = entity.NgayTaoDonHang.HasValue ? (object) entity.NgayTaoDonHang  : System.DBNull.Value;
							
				
					row["MaKhuyenMai"] = entity.MaKhuyenMai;
							
				
					row["MaVoucher"] = entity.MaVoucher;
							
				
					row["GhiChu"] = entity.GhiChu;
							
				
					row["TienChietKhau"] = entity.TienChietKhau.HasValue ? (object) entity.TienChietKhau  : System.DBNull.Value;
							
				
					row["TiLeChietKhau"] = entity.TiLeChietKhau.HasValue ? (object) entity.TiLeChietKhau  : System.DBNull.Value;
							
				
					row["IsDeleted"] = entity.IsDeleted;
							
				
				dataTable.Rows.Add(row);
			}		
			
			// send the data to the server		
			bulkCopy.WriteToServer(dataTable);		
			
			// update back the state
			foreach(SkinCare.Entities.DonHang entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
			
				entity.AcceptChanges();
			}
		}
				
		/// <summary>
		/// 	Inserts a SkinCare.Entities.DonHang object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">SkinCare.Entities.DonHang object to insert.</param>
		/// <remarks>
		///		After inserting into the datasource, the SkinCare.Entities.DonHang object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Insert(TransactionManager transactionManager, SkinCare.Entities.DonHang entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_Insert", _useStoredProcedure);
			
			database.AddOutParameter(commandWrapper, "@MaDonHang", DbType.Int32, 4);
			database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, (entity.MaKhachHang.HasValue ? (object) entity.MaKhachHang  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@MaNguonDonHang", DbType.Int32, (entity.MaNguonDonHang.HasValue ? (object) entity.MaNguonDonHang  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@MaTrangThaiDonHang", DbType.Int32, (entity.MaTrangThaiDonHang.HasValue ? (object) entity.MaTrangThaiDonHang  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@NguoiDatHang", DbType.String, entity.NguoiDatHang );
			database.AddInParameter(commandWrapper, "@MaPhuongThucThanhToan", DbType.Int32, (entity.MaPhuongThucThanhToan.HasValue ? (object) entity.MaPhuongThucThanhToan  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@CachThucNhanHang", DbType.String, entity.CachThucNhanHang );
			database.AddInParameter(commandWrapper, "@PhiVanChuyen", DbType.Decimal, (entity.PhiVanChuyen.HasValue ? (object) entity.PhiVanChuyen  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@TongTienDonHang", DbType.Decimal, (entity.TongTienDonHang.HasValue ? (object) entity.TongTienDonHang  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@NgayTaoDonHang", DbType.DateTime, (entity.NgayTaoDonHang.HasValue ? (object) entity.NgayTaoDonHang  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@MaKhuyenMai", DbType.String, entity.MaKhuyenMai );
            database.AddInParameter(commandWrapper, "@MaVoucher", DbType.String, entity.MaVoucher );
            database.AddInParameter(commandWrapper, "@GhiChu", DbType.String, entity.GhiChu );
			database.AddInParameter(commandWrapper, "@TienChietKhau", DbType.Decimal, (entity.TienChietKhau.HasValue ? (object) entity.TienChietKhau  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@TiLeChietKhau", DbType.Double, (entity.TiLeChietKhau.HasValue ? (object) entity.TiLeChietKhau  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@IsDeleted", DbType.Boolean, entity.IsDeleted );
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Insert", entity));
				
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
					
			object _maDonHang = database.GetParameterValue(commandWrapper, "@MaDonHang");
			entity.MaDonHang = (System.Int32)_maDonHang;
			
			
			entity.AcceptChanges();
	
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Insert", entity));

			return Convert.ToBoolean(results);
		}	
		#endregion

		#region Update Methods
				
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">SkinCare.Entities.DonHang object to update.</param>
		/// <remarks>
		///		After updating the datasource, the SkinCare.Entities.DonHang object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Update(TransactionManager transactionManager, SkinCare.Entities.DonHang entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblDonHang_Update", _useStoredProcedure);
			
            database.AddInParameter(commandWrapper, "@MaDonHang", DbType.Int32, entity.MaDonHang );
			database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, (entity.MaKhachHang.HasValue ? (object) entity.MaKhachHang : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@MaNguonDonHang", DbType.Int32, (entity.MaNguonDonHang.HasValue ? (object) entity.MaNguonDonHang : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@MaTrangThaiDonHang", DbType.Int32, (entity.MaTrangThaiDonHang.HasValue ? (object) entity.MaTrangThaiDonHang : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@NguoiDatHang", DbType.String, entity.NguoiDatHang );
			database.AddInParameter(commandWrapper, "@MaPhuongThucThanhToan", DbType.Int32, (entity.MaPhuongThucThanhToan.HasValue ? (object) entity.MaPhuongThucThanhToan : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@CachThucNhanHang", DbType.String, entity.CachThucNhanHang );
			database.AddInParameter(commandWrapper, "@PhiVanChuyen", DbType.Decimal, (entity.PhiVanChuyen.HasValue ? (object) entity.PhiVanChuyen : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@TongTienDonHang", DbType.Decimal, (entity.TongTienDonHang.HasValue ? (object) entity.TongTienDonHang : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@NgayTaoDonHang", DbType.DateTime, (entity.NgayTaoDonHang.HasValue ? (object) entity.NgayTaoDonHang : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@MaKhuyenMai", DbType.String, entity.MaKhuyenMai );
            database.AddInParameter(commandWrapper, "@MaVoucher", DbType.String, entity.MaVoucher );
            database.AddInParameter(commandWrapper, "@GhiChu", DbType.String, entity.GhiChu );
			database.AddInParameter(commandWrapper, "@TienChietKhau", DbType.Decimal, (entity.TienChietKhau.HasValue ? (object) entity.TienChietKhau : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@TiLeChietKhau", DbType.Double, (entity.TiLeChietKhau.HasValue ? (object) entity.TiLeChietKhau : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@IsDeleted", DbType.Boolean, entity.IsDeleted );
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Update", entity));

			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
            {
                EntityManager.StopTracking(entity.EntityTrackingKey);				
            }
			
			
			entity.AcceptChanges();
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Update", entity));

			return Convert.ToBoolean(results);
		}
			
		#endregion
		
		#region Custom Methods
	
		#endregion
	}//end class
} // end namespace
