/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file SqlKhachHangProvider.cs instead.
*/

#region using directives

using System;
using System.Data;
using System.Data.Common;
using System.Text;

using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;

using System.Collections;
using System.Collections.Specialized;

using System.Diagnostics;
using SkinCare.Entities;
using SkinCare.Data;
using SkinCare.Data.Bases;

#endregion

namespace SkinCare.Data.SqlClient
{
	///<summary>
	/// This class is the SqlClient Data Access Logic Component implementation for the <see cref="KhachHang"/> entity.
	///</summary>
	public abstract partial class SqlKhachHangProviderBase : KhachHangProviderBase
	{
		#region Declarations
		
		string _connectionString;
	    bool _useStoredProcedure;
	    string _providerInvariantName;
			
		#endregion "Declarations"
			
		#region Constructors
		
		/// <summary>
		/// Creates a new <see cref="SqlKhachHangProviderBase"/> instance.
		/// </summary>
		public SqlKhachHangProviderBase()
		{
		}
	
	/// <summary>
	/// Creates a new <see cref="SqlKhachHangProviderBase"/> instance.
	/// Uses connection string to connect to datasource.
	/// </summary>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="useStoredProcedure">A boolean value that indicates if we should use stored procedures or embedded queries.</param>
	/// <param name="providerInvariantName">Name of the invariant provider use by the DbProviderFactory.</param>
	public SqlKhachHangProviderBase(string connectionString, bool useStoredProcedure, string providerInvariantName)
	{
		this._connectionString = connectionString;
		this._useStoredProcedure = useStoredProcedure;
		this._providerInvariantName = providerInvariantName;
	}
		
	#endregion "Constructors"
	
		#region Public properties
	/// <summary>
    /// Gets or sets the connection string.
    /// </summary>
    /// <value>The connection string.</value>
    public string ConnectionString
	{
		get {return this._connectionString;}
		set {this._connectionString = value;}
	}
	
	/// <summary>
    /// Gets or sets a value indicating whether to use stored procedures.
    /// </summary>
    /// <value><c>true</c> if we choose to use use stored procedures; otherwise, <c>false</c>.</value>
	public bool UseStoredProcedure
	{
		get {return this._useStoredProcedure;}
		set {this._useStoredProcedure = value;}
	}
	
	/// <summary>
    /// Gets or sets the invariant provider name listed in the DbProviderFactories machine.config section.
    /// </summary>
    /// <value>The name of the provider invariant.</value>
    public string ProviderInvariantName
    {
        get { return this._providerInvariantName; }
        set { this._providerInvariantName = value; }
    }
	#endregion
	
		#region Get Many To Many Relationship Functions
		#endregion
	
		#region Delete Functions
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="_maKhachHang">. Primary Key.</param>	
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Delete(TransactionManager transactionManager, System.Int32 _maKhachHang)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_Delete", _useStoredProcedure);
			database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, _maKhachHang);
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Delete")); 

			int results = 0;
			
			if (transactionManager != null)
			{	
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
			{
				string entityKey = EntityLocator.ConstructKeyFromPkItems(typeof(KhachHang)
					,_maKhachHang);
                EntityManager.StopTracking(entityKey);
                
			}
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Delete")); 

			commandWrapper = null;
			
			return Convert.ToBoolean(results);
		}//end Delete
		#endregion

		#region Find Functions

		#region Parsed Find Methods
		/// <summary>
		/// 	Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks>Operators must be capitalized (OR, AND).</remarks>
		/// <returns>Returns a typed collection of SkinCare.Entities.KhachHang objects.</returns>
		public override TList<KhachHang> Find(TransactionManager transactionManager, string whereClause, int start, int pageLength, out int count)
		{
			count = -1;
			if (whereClause.IndexOf(";") > -1)
				return new TList<KhachHang>();
	
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_Find", _useStoredProcedure);

		bool searchUsingOR = false;
		if (whereClause.IndexOf(" OR ") > 0) // did they want to do "a=b OR c=d OR..."?
			searchUsingOR = true;
		
		database.AddInParameter(commandWrapper, "@SearchUsingOR", DbType.Boolean, searchUsingOR);
		
		database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TenKhachHang", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Email", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@SoDienThoai", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@DiaChi", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@GioiTinh", DbType.AnsiStringFixedLength, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TayTrangToi", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@RuaMat", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Toner", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Serum", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Kem", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@SanPhamKhac", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Luuy", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ImageLink", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Ngaysinh", DbType.DateTime, DBNull.Value);
	
			// replace all instances of 'AND' and 'OR' because we already set searchUsingOR
			whereClause = whereClause.Replace(" AND ", "|").Replace(" OR ", "|") ; 
			string[] clauses = whereClause.ToLower().Split('|');
		
			// Here's what's going on below: Find a field, then to get the value we
			// drop the field name from the front, trim spaces, drop the '=' sign,
			// trim more spaces, and drop any outer single quotes.
			// Now handles the case when two fields start off the same way - like "Friendly='Yes' AND Friend='john'"
				
			char[] equalSign = {'='};
			char[] singleQuote = {'\''};
	   		foreach (string clause in clauses)
			{
				if (clause.Trim().StartsWith("makhachhang ") || clause.Trim().StartsWith("makhachhang="))
				{
					database.SetParameterValue(commandWrapper, "@MaKhachHang", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tenkhachhang ") || clause.Trim().StartsWith("tenkhachhang="))
				{
					database.SetParameterValue(commandWrapper, "@TenKhachHang", 
						clause.Trim().Remove(0,12).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("email ") || clause.Trim().StartsWith("email="))
				{
					database.SetParameterValue(commandWrapper, "@Email", 
						clause.Trim().Remove(0,5).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("sodienthoai ") || clause.Trim().StartsWith("sodienthoai="))
				{
					database.SetParameterValue(commandWrapper, "@SoDienThoai", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("diachi ") || clause.Trim().StartsWith("diachi="))
				{
					database.SetParameterValue(commandWrapper, "@DiaChi", 
						clause.Trim().Remove(0,6).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("gioitinh ") || clause.Trim().StartsWith("gioitinh="))
				{
					database.SetParameterValue(commandWrapper, "@GioiTinh", 
						clause.Trim().Remove(0,8).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("taytrangtoi ") || clause.Trim().StartsWith("taytrangtoi="))
				{
					database.SetParameterValue(commandWrapper, "@TayTrangToi", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ruamat ") || clause.Trim().StartsWith("ruamat="))
				{
					database.SetParameterValue(commandWrapper, "@RuaMat", 
						clause.Trim().Remove(0,6).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("toner ") || clause.Trim().StartsWith("toner="))
				{
					database.SetParameterValue(commandWrapper, "@Toner", 
						clause.Trim().Remove(0,5).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("serum ") || clause.Trim().StartsWith("serum="))
				{
					database.SetParameterValue(commandWrapper, "@Serum", 
						clause.Trim().Remove(0,5).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("kem ") || clause.Trim().StartsWith("kem="))
				{
					database.SetParameterValue(commandWrapper, "@Kem", 
						clause.Trim().Remove(0,3).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("sanphamkhac ") || clause.Trim().StartsWith("sanphamkhac="))
				{
					database.SetParameterValue(commandWrapper, "@SanPhamKhac", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("luuy ") || clause.Trim().StartsWith("luuy="))
				{
					database.SetParameterValue(commandWrapper, "@Luuy", 
						clause.Trim().Remove(0,4).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("imagelink ") || clause.Trim().StartsWith("imagelink="))
				{
					database.SetParameterValue(commandWrapper, "@ImageLink", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ngaysinh ") || clause.Trim().StartsWith("ngaysinh="))
				{
					database.SetParameterValue(commandWrapper, "@Ngaysinh", 
						clause.Trim().Remove(0,8).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
	
				throw new ArgumentException("Unable to use this part of the where clause in this version of Find: " + clause);
			}
					
			IDataReader reader = null;
			//Create Collection
			TList<KhachHang> rows = new TList<KhachHang>();
	
				
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
				
				Fill(reader, rows, start, pageLength);
				
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if (reader != null) 
					reader.Close();	
					
				commandWrapper = null;
			}
			return rows;
		}

		#endregion Parsed Find Methods
		
		#region Parameterized Find Methods
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of SkinCare.Entities.KhachHang objects.</returns>
		public override TList<KhachHang> Find(TransactionManager transactionManager, IFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			SqlFilterParameterCollection filter = null;
			
			if (parameters == null)
				filter = new SqlFilterParameterCollection();
			else 
				filter = parameters.GetParameters();
				
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_Find_Dynamic", typeof(KhachHangColumn), filter, orderBy, start, pageLength);
		
			SqlFilterParameter param;

			for ( int i = 0; i < filter.Count; i++ )
			{
				param = filter[i];
				database.AddInParameter(commandWrapper, param.Name, param.DbType, param.GetValue());
			}

			TList<KhachHang> rows = new TList<KhachHang>();
			IDataReader reader = null;
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if ( transactionManager != null )
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;
				
				if ( reader.NextResult() )
				{
					if ( reader.Read() )
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if ( reader != null )
					reader.Close();
					
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion Parameterized Find Methods
		
		#endregion Find Functions
	
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of SkinCare.Entities.KhachHang objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override TList<KhachHang> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_Get_List", _useStoredProcedure);
			
			IDataReader reader = null;
		
			//Create Collection
			TList<KhachHang> rows = new TList<KhachHang>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
					
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;	
			}
			return rows;
		}//end getall
		
		#endregion
				
		#region GetPaged Methods
				
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of SkinCare.Entities.KhachHang objects.</returns>
		public override TList<KhachHang> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_GetPaged", _useStoredProcedure);
		
			
            if (commandWrapper.CommandType == CommandType.Text
                && commandWrapper.CommandText != null)
            {
                commandWrapper.CommandText = commandWrapper.CommandText.Replace(SqlUtil.PAGE_INDEX, string.Concat(SqlUtil.PAGE_INDEX, Guid.NewGuid().ToString("N").Substring(0, 8)));
            }
			
			database.AddInParameter(commandWrapper, "@WhereClause", DbType.String, whereClause);
			database.AddInParameter(commandWrapper, "@OrderBy", DbType.String, orderBy);
			database.AddInParameter(commandWrapper, "@PageIndex", DbType.Int32, start);
			database.AddInParameter(commandWrapper, "@PageSize", DbType.Int32, pageLength);
		
			IDataReader reader = null;
			//Create Collection
			TList<KhachHang> rows = new TList<KhachHang>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;

				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

			}
			catch(Exception)
			{			
				throw;
			}
			finally
			{
				if (reader != null) 
					reader.Close();
				
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion	
		
		#region Get By Foreign Key Functions
	#endregion
	
		#region Get By Index Functions

		#region GetByMaKhachHang
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_tblKhachHang index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_maKhachHang"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query.</param>
		/// <returns>Returns an instance of the <see cref="SkinCare.Entities.KhachHang"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override SkinCare.Entities.KhachHang GetByMaKhachHang(TransactionManager transactionManager, System.Int32 _maKhachHang, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_GetByMaKhachHang", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, _maKhachHang);
			
			IDataReader reader = null;
			TList<KhachHang> tmp = new TList<KhachHang>();
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetByMaKhachHang", tmp)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetByMaKhachHang", tmp));
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;
			}
			
			if (tmp.Count == 1)
			{
				return tmp[0];
			}
			else if (tmp.Count == 0)
			{
				return null;
			}
			else
			{
				throw new DataException("Cannot find the unique instance of the class.");
			}
			
			//return rows;
		}
		
		#endregion

	#endregion Get By Index Functions

		#region Insert Methods
		/// <summary>
		/// Lets you efficiently bulk insert many entities to the database.
		/// </summary>
		/// <param name="transactionManager">The transaction manager.</param>
		/// <param name="entities">The entities.</param>
		/// <remarks>
		///		After inserting into the datasource, the SkinCare.Entities.KhachHang object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		public override void BulkInsert(TransactionManager transactionManager, TList<SkinCare.Entities.KhachHang> entities)
		{
			//System.Data.SqlClient.SqlBulkCopy bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			
			System.Data.SqlClient.SqlBulkCopy bulkCopy = null;
	
			if (transactionManager != null && transactionManager.IsOpen)
			{			
				System.Data.SqlClient.SqlConnection cnx = transactionManager.TransactionObject.Connection as System.Data.SqlClient.SqlConnection;
				System.Data.SqlClient.SqlTransaction transaction = transactionManager.TransactionObject as System.Data.SqlClient.SqlTransaction;
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, transaction); //, null);
			}
			else
			{
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			}
			
			bulkCopy.BulkCopyTimeout = 360;
			bulkCopy.DestinationTableName = "tblKhachHang";
			
			DataTable dataTable = new DataTable();
			DataColumn col0 = dataTable.Columns.Add("MaKhachHang", typeof(System.Int32));
			col0.AllowDBNull = false;		
			DataColumn col1 = dataTable.Columns.Add("TenKhachHang", typeof(System.String));
			col1.AllowDBNull = true;		
			DataColumn col2 = dataTable.Columns.Add("Email", typeof(System.String));
			col2.AllowDBNull = true;		
			DataColumn col3 = dataTable.Columns.Add("SoDienThoai", typeof(System.String));
			col3.AllowDBNull = true;		
			DataColumn col4 = dataTable.Columns.Add("DiaChi", typeof(System.String));
			col4.AllowDBNull = true;		
			DataColumn col5 = dataTable.Columns.Add("GioiTinh", typeof(System.String));
			col5.AllowDBNull = true;		
			DataColumn col6 = dataTable.Columns.Add("TayTrangToi", typeof(System.Boolean));
			col6.AllowDBNull = true;		
			DataColumn col7 = dataTable.Columns.Add("RuaMat", typeof(System.Boolean));
			col7.AllowDBNull = true;		
			DataColumn col8 = dataTable.Columns.Add("Toner", typeof(System.Boolean));
			col8.AllowDBNull = true;		
			DataColumn col9 = dataTable.Columns.Add("Serum", typeof(System.Boolean));
			col9.AllowDBNull = true;		
			DataColumn col10 = dataTable.Columns.Add("Kem", typeof(System.Boolean));
			col10.AllowDBNull = true;		
			DataColumn col11 = dataTable.Columns.Add("SanPhamKhac", typeof(System.Boolean));
			col11.AllowDBNull = true;		
			DataColumn col12 = dataTable.Columns.Add("LuuY", typeof(System.String));
			col12.AllowDBNull = true;		
			DataColumn col13 = dataTable.Columns.Add("ImageLink", typeof(System.String));
			col13.AllowDBNull = true;		
			DataColumn col14 = dataTable.Columns.Add("Ngaysinh", typeof(System.DateTime));
			col14.AllowDBNull = true;		
			
			bulkCopy.ColumnMappings.Add("MaKhachHang", "MaKhachHang");
			bulkCopy.ColumnMappings.Add("TenKhachHang", "TenKhachHang");
			bulkCopy.ColumnMappings.Add("Email", "Email");
			bulkCopy.ColumnMappings.Add("SoDienThoai", "SoDienThoai");
			bulkCopy.ColumnMappings.Add("DiaChi", "DiaChi");
			bulkCopy.ColumnMappings.Add("GioiTinh", "GioiTinh");
			bulkCopy.ColumnMappings.Add("TayTrangToi", "TayTrangToi");
			bulkCopy.ColumnMappings.Add("RuaMat", "RuaMat");
			bulkCopy.ColumnMappings.Add("Toner", "Toner");
			bulkCopy.ColumnMappings.Add("Serum", "Serum");
			bulkCopy.ColumnMappings.Add("Kem", "Kem");
			bulkCopy.ColumnMappings.Add("SanPhamKhac", "SanPhamKhac");
			bulkCopy.ColumnMappings.Add("LuuY", "LuuY");
			bulkCopy.ColumnMappings.Add("ImageLink", "ImageLink");
			bulkCopy.ColumnMappings.Add("Ngaysinh", "Ngaysinh");
			
			foreach(SkinCare.Entities.KhachHang entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
					
				DataRow row = dataTable.NewRow();
				
					row["MaKhachHang"] = entity.MaKhachHang;
							
				
					row["TenKhachHang"] = entity.TenKhachHang;
							
				
					row["Email"] = entity.Email;
							
				
					row["SoDienThoai"] = entity.SoDienThoai;
							
				
					row["DiaChi"] = entity.DiaChi;
							
				
					row["GioiTinh"] = entity.GioiTinh;
							
				
					row["TayTrangToi"] = entity.TayTrangToi.HasValue ? (object) entity.TayTrangToi  : System.DBNull.Value;
							
				
					row["RuaMat"] = entity.RuaMat.HasValue ? (object) entity.RuaMat  : System.DBNull.Value;
							
				
					row["Toner"] = entity.Toner.HasValue ? (object) entity.Toner  : System.DBNull.Value;
							
				
					row["Serum"] = entity.Serum.HasValue ? (object) entity.Serum  : System.DBNull.Value;
							
				
					row["Kem"] = entity.Kem.HasValue ? (object) entity.Kem  : System.DBNull.Value;
							
				
					row["SanPhamKhac"] = entity.SanPhamKhac.HasValue ? (object) entity.SanPhamKhac  : System.DBNull.Value;
							
				
					row["LuuY"] = entity.Luuy;
							
				
					row["ImageLink"] = entity.ImageLink;
							
				
					row["Ngaysinh"] = entity.Ngaysinh.HasValue ? (object) entity.Ngaysinh  : System.DBNull.Value;
							
				
				dataTable.Rows.Add(row);
			}		
			
			// send the data to the server		
			bulkCopy.WriteToServer(dataTable);		
			
			// update back the state
			foreach(SkinCare.Entities.KhachHang entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
			
				entity.AcceptChanges();
			}
		}
				
		/// <summary>
		/// 	Inserts a SkinCare.Entities.KhachHang object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">SkinCare.Entities.KhachHang object to insert.</param>
		/// <remarks>
		///		After inserting into the datasource, the SkinCare.Entities.KhachHang object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Insert(TransactionManager transactionManager, SkinCare.Entities.KhachHang entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_Insert", _useStoredProcedure);
			
			database.AddOutParameter(commandWrapper, "@MaKhachHang", DbType.Int32, 4);
            database.AddInParameter(commandWrapper, "@TenKhachHang", DbType.String, entity.TenKhachHang );
            database.AddInParameter(commandWrapper, "@Email", DbType.String, entity.Email );
            database.AddInParameter(commandWrapper, "@SoDienThoai", DbType.String, entity.SoDienThoai );
            database.AddInParameter(commandWrapper, "@DiaChi", DbType.String, entity.DiaChi );
            database.AddInParameter(commandWrapper, "@GioiTinh", DbType.AnsiStringFixedLength, entity.GioiTinh );
			database.AddInParameter(commandWrapper, "@TayTrangToi", DbType.Boolean, (entity.TayTrangToi.HasValue ? (object) entity.TayTrangToi  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@RuaMat", DbType.Boolean, (entity.RuaMat.HasValue ? (object) entity.RuaMat  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Toner", DbType.Boolean, (entity.Toner.HasValue ? (object) entity.Toner  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Serum", DbType.Boolean, (entity.Serum.HasValue ? (object) entity.Serum  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Kem", DbType.Boolean, (entity.Kem.HasValue ? (object) entity.Kem  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@SanPhamKhac", DbType.Boolean, (entity.SanPhamKhac.HasValue ? (object) entity.SanPhamKhac  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Luuy", DbType.String, entity.Luuy );
            database.AddInParameter(commandWrapper, "@ImageLink", DbType.String, entity.ImageLink );
			database.AddInParameter(commandWrapper, "@Ngaysinh", DbType.DateTime, (entity.Ngaysinh.HasValue ? (object) entity.Ngaysinh  : System.DBNull.Value));
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Insert", entity));
				
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
					
			object _maKhachHang = database.GetParameterValue(commandWrapper, "@MaKhachHang");
			entity.MaKhachHang = (System.Int32)_maKhachHang;
			
			
			entity.AcceptChanges();
	
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Insert", entity));

			return Convert.ToBoolean(results);
		}	
		#endregion

		#region Update Methods
				
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">SkinCare.Entities.KhachHang object to update.</param>
		/// <remarks>
		///		After updating the datasource, the SkinCare.Entities.KhachHang object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Update(TransactionManager transactionManager, SkinCare.Entities.KhachHang entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.tblKhachHang_Update", _useStoredProcedure);
			
            database.AddInParameter(commandWrapper, "@MaKhachHang", DbType.Int32, entity.MaKhachHang );
            database.AddInParameter(commandWrapper, "@TenKhachHang", DbType.String, entity.TenKhachHang );
            database.AddInParameter(commandWrapper, "@Email", DbType.String, entity.Email );
            database.AddInParameter(commandWrapper, "@SoDienThoai", DbType.String, entity.SoDienThoai );
            database.AddInParameter(commandWrapper, "@DiaChi", DbType.String, entity.DiaChi );
            database.AddInParameter(commandWrapper, "@GioiTinh", DbType.AnsiStringFixedLength, entity.GioiTinh );
			database.AddInParameter(commandWrapper, "@TayTrangToi", DbType.Boolean, (entity.TayTrangToi.HasValue ? (object) entity.TayTrangToi : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@RuaMat", DbType.Boolean, (entity.RuaMat.HasValue ? (object) entity.RuaMat : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Toner", DbType.Boolean, (entity.Toner.HasValue ? (object) entity.Toner : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Serum", DbType.Boolean, (entity.Serum.HasValue ? (object) entity.Serum : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Kem", DbType.Boolean, (entity.Kem.HasValue ? (object) entity.Kem : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@SanPhamKhac", DbType.Boolean, (entity.SanPhamKhac.HasValue ? (object) entity.SanPhamKhac : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@Luuy", DbType.String, entity.Luuy );
            database.AddInParameter(commandWrapper, "@ImageLink", DbType.String, entity.ImageLink );
			database.AddInParameter(commandWrapper, "@Ngaysinh", DbType.DateTime, (entity.Ngaysinh.HasValue ? (object) entity.Ngaysinh : System.DBNull.Value) );
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Update", entity));

			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
            {
                EntityManager.StopTracking(entity.EntityTrackingKey);				
            }
			
			
			entity.AcceptChanges();
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Update", entity));

			return Convert.ToBoolean(results);
		}
			
		#endregion
		
		#region Custom Methods
	

		#region _tblKhachHang_GetLastId
					
		/// <summary>
		///	This method wraps the '_tblKhachHang_GetLastId' stored procedure. 
		/// </summary>	
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object.</param>
		/// <remark>This method is generated from a stored procedure.</remark>
		/// <returns>A <see cref="DataSet"/> instance.</returns>
		public override DataSet GetLastId(TransactionManager transactionManager, int start, int pageLength )
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo._tblKhachHang_GetLastId", true);
			
	
			
			DataSet ds = null;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "GetLastId", (IEntity)null));

			if (transactionManager != null)
			{	
				ds = Utility.ExecuteDataSet(transactionManager, commandWrapper);
			}
			else
			{
				ds = Utility.ExecuteDataSet(database, commandWrapper);
			}
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "GetLastId", (IEntity)null));

			

			
			return ds;	
		}
		#endregion
		#endregion
	}//end class
} // end namespace
